
-- Creatives generated by AI
CREATE TABLE public.ads_studio_creatives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  campaign_id UUID REFERENCES public.store_ad_campaigns(id) ON DELETE SET NULL,
  goal TEXT NOT NULL DEFAULT 'traffic',
  service_ids UUID[] DEFAULT '{}',
  targeting JSONB DEFAULT '{}'::jsonb,
  budget JSONB DEFAULT '{}'::jsonb,
  headlines JSONB DEFAULT '[]'::jsonb,
  descriptions JSONB DEFAULT '[]'::jsonb,
  ctas JSONB DEFAULT '[]'::jsonb,
  image_urls JSONB DEFAULT '[]'::jsonb,
  video_scripts JSONB DEFAULT '[]'::jsonb,
  hashtags JSONB DEFAULT '[]'::jsonb,
  platforms TEXT[] DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'draft',
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ads_studio_creatives_store ON public.ads_studio_creatives(store_id, created_at DESC);

-- Generation log (for billing & analytics)
CREATE TABLE public.ads_studio_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  creative_id UUID REFERENCES public.ads_studio_creatives(id) ON DELETE SET NULL,
  generation_type TEXT NOT NULL, -- 'copy' | 'image' | 'video_script'
  model TEXT,
  cost_cents INTEGER NOT NULL DEFAULT 0,
  meta JSONB DEFAULT '{}'::jsonb,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ads_studio_generations_store ON public.ads_studio_generations(store_id, created_at DESC);

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.tg_ads_studio_creatives_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER trg_ads_studio_creatives_updated_at
BEFORE UPDATE ON public.ads_studio_creatives
FOR EACH ROW EXECUTE FUNCTION public.tg_ads_studio_creatives_updated_at();

-- RLS
ALTER TABLE public.ads_studio_creatives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_studio_generations ENABLE ROW LEVEL SECURITY;

-- Helper: caller owns the store
CREATE OR REPLACE FUNCTION public.is_store_owner(_store_id UUID, _user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.restaurants r
    WHERE r.id = _store_id AND r.owner_id = _user_id
  );
$$;

-- Creatives policies
CREATE POLICY "owner_select_creatives" ON public.ads_studio_creatives
FOR SELECT TO authenticated
USING (public.is_store_owner(store_id, auth.uid()));

CREATE POLICY "owner_insert_creatives" ON public.ads_studio_creatives
FOR INSERT TO authenticated
WITH CHECK (public.is_store_owner(store_id, auth.uid()));

CREATE POLICY "owner_update_creatives" ON public.ads_studio_creatives
FOR UPDATE TO authenticated
USING (public.is_store_owner(store_id, auth.uid()))
WITH CHECK (public.is_store_owner(store_id, auth.uid()));

CREATE POLICY "owner_delete_creatives" ON public.ads_studio_creatives
FOR DELETE TO authenticated
USING (public.is_store_owner(store_id, auth.uid()));

-- Generations policies (read-only for owner; writes via service role in edge fn)
CREATE POLICY "owner_select_generations" ON public.ads_studio_generations
FOR SELECT TO authenticated
USING (public.is_store_owner(store_id, auth.uid()));

-- Storage bucket for generated images
INSERT INTO storage.buckets (id, name, public)
VALUES ('store-ad-creatives', 'store-ad-creatives', true)
ON CONFLICT (id) DO NOTHING;

-- Public read
CREATE POLICY "public_read_ad_creatives" ON storage.objects
FOR SELECT TO public
USING (bucket_id = 'store-ad-creatives');

-- Owner can upload to {storeId}/...
CREATE POLICY "owner_write_ad_creatives" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'store-ad-creatives'
  AND public.is_store_owner((storage.foldername(name))[1]::uuid, auth.uid())
);

CREATE POLICY "owner_delete_ad_creatives" ON storage.objects
FOR DELETE TO authenticated
USING (
  bucket_id = 'store-ad-creatives'
  AND public.is_store_owner((storage.foldername(name))[1]::uuid, auth.uid())
);
