ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS social_facebook TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_instagram TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_tiktok TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_snapchat TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_x TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_linkedin TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS social_links_visible BOOLEAN DEFAULT TRUE;