
-- Activate Spanish
UPDATE supported_languages SET is_active = true WHERE code = 'es';

-- Seed Spanish translations for all keys from i18n.ts
INSERT INTO ui_translations (language_code, namespace, key, value) VALUES
-- Common: Navigation
('es', 'common', 'nav.home', 'Inicio'),
('es', 'common', 'nav.flights', 'Vuelos'),
('es', 'common', 'nav.hotels', 'Hoteles'),
('es', 'common', 'nav.cars', 'Autos'),
('es', 'common', 'nav.rides', 'Viajes'),
('es', 'common', 'nav.eats', 'Comida'),
('es', 'common', 'nav.move', 'Mudanzas'),
('es', 'common', 'nav.account', 'Cuenta'),
('es', 'common', 'nav.login', 'Iniciar sesión'),
('es', 'common', 'nav.signup', 'Registrarse'),
('es', 'common', 'nav.logout', 'Cerrar sesión'),
-- Common: Actions
('es', 'common', 'action.search', 'Buscar'),
('es', 'common', 'action.book', 'Reservar ahora'),
('es', 'common', 'action.continue', 'Continuar'),
('es', 'common', 'action.cancel', 'Cancelar'),
('es', 'common', 'action.save', 'Guardar'),
('es', 'common', 'action.edit', 'Editar'),
('es', 'common', 'action.delete', 'Eliminar'),
('es', 'common', 'action.view', 'Ver'),
('es', 'common', 'action.back', 'Atrás'),
('es', 'common', 'action.next', 'Siguiente'),
('es', 'common', 'action.submit', 'Enviar'),
('es', 'common', 'action.confirm', 'Confirmar'),
('es', 'common', 'action.close', 'Cerrar'),
-- Common: Status
('es', 'common', 'status.loading', 'Cargando...'),
('es', 'common', 'status.error', 'Ocurrió un error'),
('es', 'common', 'status.success', 'Éxito'),
('es', 'common', 'status.pending', 'Pendiente'),
('es', 'common', 'status.completed', 'Completado'),
('es', 'common', 'status.cancelled', 'Cancelado'),
-- Common: Time
('es', 'common', 'time.today', 'Hoy'),
('es', 'common', 'time.tomorrow', 'Mañana'),
('es', 'common', 'time.yesterday', 'Ayer'),
-- Common: Currency
('es', 'common', 'currency.from', 'Desde'),
('es', 'common', 'currency.total', 'Total'),
('es', 'common', 'currency.subtotal', 'Subtotal'),
('es', 'common', 'currency.tax', 'Impuesto'),
('es', 'common', 'currency.fee', 'Tarifa'),
-- Common: Legal
('es', 'common', 'legal.terms', 'Términos de servicio'),
('es', 'common', 'legal.privacy', 'Política de privacidad'),
('es', 'common', 'legal.cookies', 'Política de cookies'),
('es', 'common', 'legal.partner_disclosure', 'Divulgación de socios'),
-- Common: Errors
('es', 'common', 'error.generic', 'Algo salió mal. Por favor, inténtelo de nuevo.'),
('es', 'common', 'error.network', 'Error de red. Verifique su conexión.'),
('es', 'common', 'error.unauthorized', 'Inicie sesión para continuar.'),
('es', 'common', 'error.not_found', 'Página no encontrada.'),
-- Flights
('es', 'flights', 'flights.search_title', 'Buscar vuelos'),
('es', 'flights', 'flights.from', 'Desde'),
('es', 'flights', 'flights.to', 'Hacia'),
('es', 'flights', 'flights.departure', 'Salida'),
('es', 'flights', 'flights.return', 'Regreso'),
('es', 'flights', 'flights.passengers', 'Pasajeros'),
('es', 'flights', 'flights.class', 'Clase'),
('es', 'flights', 'flights.roundtrip', 'Ida y vuelta'),
('es', 'flights', 'flights.oneway', 'Solo ida'),
('es', 'flights', 'flights.economy', 'Económica'),
('es', 'flights', 'flights.business', 'Ejecutiva'),
('es', 'flights', 'flights.first', 'Primera clase'),
('es', 'flights', 'flights.results', 'Resultados de vuelos'),
('es', 'flights', 'flights.no_results', 'No se encontraron vuelos'),
('es', 'flights', 'flights.price_disclaimer', 'Los precios mostrados son indicativos. El precio final se confirma en el checkout del socio.'),
-- Hotels
('es', 'hotels', 'hotels.search_title', 'Buscar hoteles'),
('es', 'hotels', 'hotels.destination', 'Destino'),
('es', 'hotels', 'hotels.checkin', 'Entrada'),
('es', 'hotels', 'hotels.checkout', 'Salida'),
('es', 'hotels', 'hotels.guests', 'Huéspedes'),
('es', 'hotels', 'hotels.rooms', 'Habitaciones'),
('es', 'hotels', 'hotels.per_night', 'por noche'),
('es', 'hotels', 'hotels.results', 'Resultados de hoteles'),
('es', 'hotels', 'hotels.no_results', 'No se encontraron hoteles'),
-- Cars
('es', 'cars', 'cars.search_title', 'Alquilar un auto'),
('es', 'cars', 'cars.pickup_location', 'Lugar de recogida'),
('es', 'cars', 'cars.dropoff_location', 'Lugar de devolución'),
('es', 'cars', 'cars.pickup_date', 'Fecha de recogida'),
('es', 'cars', 'cars.dropoff_date', 'Fecha de devolución'),
('es', 'cars', 'cars.per_day', 'por día'),
('es', 'cars', 'cars.results', 'Autos disponibles'),
('es', 'cars', 'cars.no_results', 'No hay autos disponibles'),
-- Auth
('es', 'auth', 'auth.login_title', 'Bienvenido de nuevo'),
('es', 'auth', 'auth.signup_title', 'Crear cuenta'),
('es', 'auth', 'auth.email', 'Correo electrónico'),
('es', 'auth', 'auth.password', 'Contraseña'),
('es', 'auth', 'auth.confirm_password', 'Confirmar contraseña'),
('es', 'auth', 'auth.forgot_password', '¿Olvidaste tu contraseña?'),
('es', 'auth', 'auth.no_account', '¿No tienes una cuenta?'),
('es', 'auth', 'auth.have_account', '¿Ya tienes una cuenta?')
ON CONFLICT DO NOTHING;
