import { useI18n } from "@/hooks/useI18n";
const khmer: Record<string, string> = {
  "Add to home screen": "បន្ថែមទៅអេក្រង់ដើម",
  "Flights": "ជើងហោះហើរ", "Search Flights": "ស្វែងរកជើងហោះហើរ", "Popular Destinations": "គោលដៅពេញនិយម", "Price Alerts": "ការជូនដំណឹងតម្លៃ", "Deals": "ការផ្តល់ជូន", "Find Hotels": "ស្វែងរកសណ្ឋាគារ", "Top Cities": "ទីក្រុងពេញនិយម", "Hotel Deals": "ការផ្តល់ជូនសណ្ឋាគារ", "Cars & More": "រថយន្ត និងសេវាបន្ថែម", "Car Rentals": "ជួលរថយន្ត", "P2P Rentals": "ជួលពីម្ចាស់ផ្ទាល់", "Bus Tickets": "សំបុត្ររថយន្តក្រុង", "Become a Driver": "ក្លាយជាអ្នកបើកបរ", "Company": "ក្រុមហ៊ុន", "About ZIVO": "អំពី ZIVO", "How It Works": "របៀបប្រើប្រាស់", "Careers": "ការងារ", "Press": "ព័ត៌មានសារព័ត៌មាន", "FAQ": "សំណួរញឹកញាប់", "Help Center": "មជ្ឈមណ្ឌលជំនួយ", "Support Tickets": "សំណើជំនួយ", "System Status": "ស្ថានភាពប្រព័ន្ធ", "My Trips": "ដំណើររបស់ខ្ញុំ", "Wallet": "កាបូប", "Payment Methods": "មធ្យោបាយទូទាត់", "Destinations": "គោលដៅ", "Cars & Bus": "រថយន្ត និងរថយន្តក្រុង", "Rental Cars": "រថយន្តជួល", "Travel Support": "ជំនួយដំណើរ", "Account": "គណនី", "Contact": "ទំនាក់ទំនង", "Cookies": "ខូគី", "Partner Disclosure": "ព័ត៌មានដៃគូ", "Refund Policy": "គោលការណ៍សងប្រាក់", "Seller of Travel": "អ្នកលក់សេវាទេសចរណ៍", "Accessibility": "ភាពងាយស្រួលប្រើប្រាស់", "Do Not Sell My Info": "កុំលក់ព័ត៌មានរបស់ខ្ញុំ", "Book flights, hotels, and car rentals with transparent pricing and secure checkout. Your next adventure starts here.": "ស្វែងរកជើងហោះហើរ សណ្ឋាគារ និងរថយន្តជួល ជាមួយតម្លៃច្បាស់លាស់ និងការទូទាត់ដែលមានសុវត្ថិភាព។ ចាប់ផ្ដើមដំណើរបន្ទាប់របស់អ្នកនៅទីនេះ។", "Download on the": "ទាញយកនៅ", "Get it on": "ទាញយកនៅ", ". Made with": "។ បង្កើតដោយ", "for travelers.": "សម្រាប់អ្នកដំណើរ។", "Back to Top": "ត្រឡប់ទៅខាងលើ", "is an online travel agency.": "ជាភ្នាក់ងារទេសចរណ៍អនឡាញ។", "processes payments and issues travel services using authorized suppliers.": "ដំណើរការទូទាត់ និងផ្ដល់សេវាទេសចរណ៍តាមអ្នកផ្គត់ផ្គង់ដែលមានការអនុញ្ញាត។", "Registered Seller of Travel where required. CA SOT: pending · FL SOT: pending": "ការចុះបញ្ជីអ្នកលក់ទេសចរណ៍តាមតម្រូវការ។ CA SOT៖ កំពុងរង់ចាំ · FL SOT៖ កំពុងរង់ចាំ",
  "Low": "ទាប", "Mid": "មធ្យម", "High": "ខ្ពស់", "Now tap your return date": "ឥឡូវជ្រើសរើសថ្ងៃត្រឡប់", "Economy": "ថ្នាក់សន្សំសំចៃ", "Standard seating": "កៅអីស្តង់ដារ", "Premium Economy": "ថ្នាក់សន្សំសំចៃពិសេស", "Extra legroom": "កន្លែងជើងទូលាយ", "Business": "ថ្នាក់ពាណិជ្ជកម្ម", "Lie-flat seats": "កៅអីដែលអាចដេកបាន", "First Class": "ថ្នាក់ទីមួយ", "Ultimate luxury": "ផាសុកភាពពិសេស", "Travelers & Cabin": "អ្នកដំណើរ និងថ្នាក់កៅអី", "Travelers": "អ្នកដំណើរ", "travelers": "អ្នកដំណើរ", "Up to 9 passengers": "រហូតដល់អ្នកដំណើរ ៩ នាក់", "Cabin class": "ថ្នាក់កៅអី", "Departure date": "ថ្ងៃចេញដំណើរ", "Return date": "ថ្ងៃត្រឡប់", "Select dates": "ជ្រើសរើសកាលបរិច្ឆេទ", "Select date": "ជ្រើសរើសកាលបរិច្ឆេទ", "Tap departure date": "ជ្រើសរើសថ្ងៃចេញដំណើរ", "Tap a date to continue": "ជ្រើសរើសថ្ងៃដើម្បីបន្ត", "Select travel dates": "ជ្រើសរើសថ្ងៃធ្វើដំណើរ", "Price per person": "តម្លៃក្នុងម្នាក់", "Confirm dates": "បញ្ជាក់កាលបរិច្ឆេទ",
  "You haven't saved any properties yet — tap the heart on a card.": "អ្នកមិនទាន់បានរក្សាទុកកន្លែងស្នាក់នៅទេ។ ចុចរូបបេះដូងលើកាតដើម្បីរក្សាទុក។",
  "Try a different city or remove some filters.": "សាកល្បងទីក្រុងផ្សេង ឬដកតម្រងខ្លះចេញ។", "Be the first — list your property on ZIVO.": "ចុះបញ្ជីកន្លែងស្នាក់នៅរបស់អ្នកលើ ZIVO។",
  "Compare nearby travel dates when your plans are flexible.": "ប្រៀបធៀបថ្ងៃធ្វើដំណើរជិតៗគ្នា ប្រសិនបើអ្នកអាចផ្លាស់ប្ដូរផែនការបាន។", "Check baggage and change rules before choosing a fare.": "ពិនិត្យឥវ៉ាន់ និងលក្ខខណ្ឌផ្លាស់ប្ដូរ មុនជ្រើសរើសតម្លៃ។", "Review the payment methods and final total at checkout.": "ពិនិត្យមធ្យោបាយទូទាត់ និងទឹកប្រាក់សរុបចុងក្រោយ ពេលទូទាត់។", "Check the cancellation terms for your selected fare.": "ពិនិត្យលក្ខខណ្ឌលុបចោលសម្រាប់តម្លៃដែលអ្នកបានជ្រើសរើស។",
  "Which payment methods are accepted?": "តើអាចប្រើមធ្យោបាយទូទាត់អ្វីខ្លះ?", "Checkout shows the payment methods available for your booking. Review the currency and final total before confirming.": "ទំព័រទូទាត់បង្ហាញមធ្យោបាយដែលអាចប្រើបានសម្រាប់ការកក់របស់អ្នក។ ពិនិត្យរូបិយប័ណ្ណ និងទឹកប្រាក់សរុប មុនបញ្ជាក់។",
  "When do I get my e-ticket?": "តើខ្ញុំទទួលសំបុត្រអេឡិចត្រូនិកនៅពេលណា?", "Check My bookings and your confirmation email for ticketing status. A successful payment alone does not confirm that a ticket has been issued.": "ពិនិត្យការកក់របស់ខ្ញុំ និងអ៊ីមែលបញ្ជាក់ ដើម្បីដឹងស្ថានភាពចេញសំបុត្រ។ ការទូទាត់ជោគជ័យតែមួយមុខ មិនបញ្ជាក់ថាសំបុត្របានចេញរួចទេ។",
  "Can I cancel or change a flight?": "តើខ្ញុំអាចលុបចោល ឬផ្លាស់ប្ដូរជើងហោះហើរបានទេ?", "Cancellation, changes and any fees depend on the selected fare. Review the airline and partner terms before confirming.": "ការលុបចោល ការផ្លាស់ប្ដូរ និងថ្លៃសេវា អាស្រ័យលើតម្លៃដែលបានជ្រើសរើស។ ពិនិត្យលក្ខខណ្ឌក្រុមហ៊ុនអាកាសចរណ៍ និងដៃគូ មុនបញ្ជាក់។",
  "What documents do I need?": "តើខ្ញុំត្រូវការឯកសារអ្វីខ្លះ?", "Check your airline's current identity and entry requirements for your route before booking.": "ពិនិត្យតម្រូវការអត្តសញ្ញាណ និងការចូលប្រទេសបច្ចុប្បន្នរបស់ក្រុមហ៊ុនអាកាសចរណ៍ សម្រាប់ផ្លូវរបស់អ្នក មុនកក់។",
  "How much baggage is included?": "តើតម្លៃរួមបញ្ចូលឥវ៉ាន់ប៉ុន្មាន?", "Use the baggage allowance listed with your selected fare. Limits and extra charges vary by airline and fare type.": "ពិនិត្យកម្រិតឥវ៉ាន់ដែលបង្ហាញជាមួយតម្លៃដែលអ្នកបានជ្រើសរើស។ កម្រិត និងថ្លៃបន្ថែម ខុសគ្នាតាមក្រុមហ៊ុនអាកាសចរណ៍ និងប្រភេទតម្លៃ។",
  "Back": "ត្រឡប់ក្រោយ", "Zivo Travel home": "ទំព័រដើម Zivo Travel", "Manage in ZIVO Software": "គ្រប់គ្រងក្នុង ZIVO Software", "Clear search": "សម្អាតការស្វែងរក", "Search hotels and destinations (sticky)": "ស្វែងរកសណ្ឋាគារ និងគោលដៅ", "Edit dates": "កែប្រែកាលបរិច្ឆេទ", "Recent": "ថ្មីៗ", "Clear all": "សម្អាតទាំងអស់", "Near me": "នៅជិតខ្ញុំ", "Saved (": "បានរក្សាទុក (", "Saved only": "តែអ្វីដែលបានរក្សាទុក", "Popular destinations": "គោលដៅពេញនិយម", "Featured properties": "កន្លែងស្នាក់នៅពិសេស", "See all top-rated properties": "មើលកន្លែងស្នាក់នៅដែលមានពិន្ទុខ្ពស់ទាំងអស់", "See all": "មើលទាំងអស់", "Verified": "បានផ្ទៀងផ្ទាត់", "New": "ថ្មី", "from": "ចាប់ពី", "/night": "/យប់", "Recently viewed": "បានមើលថ្មីៗ", "Clear": "សម្អាត", "Hotels in": "សណ្ឋាគារនៅ", "All Hotels & Resorts": "សណ្ឋាគារ និងរមណីយដ្ឋានទាំងអស់", "List": "បញ្ជី", "Map": "ផែនទី", "Sort:": "តម្រៀប៖", "Budget:": "ថវិកា៖", "No properties found": "រកមិនឃើញកន្លែងស្នាក់នៅ", "Clear filters": "សម្អាតតម្រង", "List your property": "ចុះបញ្ជីកន្លែងស្នាក់នៅរបស់អ្នក", "Show more": "បង្ហាញបន្ថែម", "Showing": "កំពុងបង្ហាញ", "of": "ក្នុងចំណោម", "Showing all": "បង្ហាញទាំងអស់", "properties": "កន្លែងស្នាក់នៅ", "Find a hotel with AI": "ស្វែងរកសណ្ឋាគារជាមួយ AI", "Find with AI": "ស្វែងរកជាមួយ AI", "for": "សម្រាប់",
  "All": "ទាំងអស់", "Hotels": "សណ្ឋាគារ", "Resorts": "រមណីយដ្ឋាន", "Guesthouses": "ផ្ទះសំណាក់", "Beachfront": "មុខឆ្នេរ", "Pool": "អាងហែលទឹក", "Breakfast": "អាហារពេលព្រឹក", "Free Wi-Fi": "Wi-Fi ឥតគិតថ្លៃ", "Family": "គ្រួសារ", "Pet-friendly": "អនុញ្ញាតសត្វចិញ្ចឹម", "Pets": "សត្វចិញ្ចឹម", "Phnom Penh": "ភ្នំពេញ", "Siem Reap": "សៀមរាប", "Sihanoukville": "ព្រះសីហនុ", "Kep": "កែប", "Kampot": "កំពត", "Battambang": "បាត់ដំបង", "Best match": "សមស្របបំផុត", "Top rated": "ពិន្ទុខ្ពស់", "Price ↑": "តម្លៃ ↑", "Price ↓": "តម្លៃ ↓", "Any": "ទាំងអស់", "Remove from favorites": "ដកចេញពីចំណូលចិត្ត", "Save to favorites": "រក្សាទុកក្នុងចំណូលចិត្ត", "Monthly deal": "ការផ្តល់ជូនប្រចាំខែ", "Weekly deal": "ការផ្តល់ជូនប្រចាំសប្ដាហ៍", "Check availability": "ពិនិត្យភាពទំនេរ", "View property": "មើលកន្លែងស្នាក់នៅ", "No reviews yet": "មិនទាន់មានការវាយតម្លៃ", "reviews": "ការវាយតម្លៃ", "review": "ការវាយតម្លៃ", "night": "យប់", "nights": "យប់", "Adults": "មនុស្សពេញវ័យ", "Children": "កុមារ", "Rooms": "បន្ទប់", "Done": "រួចរាល់",
  "Top routes from Cambodia": "ផ្លូវហោះហើរពេញនិយមពីកម្ពុជា", "Live fares from Phnom Penh & Siem Reap": "តម្លៃបច្ចុប្បន្នពីភ្នំពេញ និងសៀមរាប", "Updated": "បានធ្វើបច្ចុប្បន្នភាព", "Loading": "កំពុងផ្ទុក", "Live Prices": "តម្លៃបច្ចុប្បន្ន", "Unavailable": "មិនអាចប្រើបាន", "Refresh prices": "ធ្វើបច្ចុប្បន្នភាពតម្លៃ", "Filter routes by origin airport": "ត្រងផ្លូវហោះហើរតាមអាកាសយានដ្ឋានចេញដំណើរ", "Live route prices unavailable right now": "តម្លៃជើងហោះហើរបច្ចុប្បន្នមិនអាចផ្ទុកបាន", "Use the search form above to request current fares from travel partners.": "ប្រើទម្រង់ស្វែងរកខាងលើ ដើម្បីស្នើសុំតម្លៃបច្ចុប្បន្នពីដៃគូទេសចរណ៍។", "Search flights": "ស្វែងរកជើងហោះហើរ", "Top airlines we compare": "ក្រុមហ៊ុនអាកាសចរណ៍ដែលយើងប្រៀបធៀប", "Why Book with ZIVO?": "ហេតុអ្វីកក់ជាមួយ ZIVO?", "Trusted by travelers worldwide": "សម្រាប់អ្នកដំណើរជុំវិញពិភពលោក", "View live routes": "មើលផ្លូវហោះហើរបច្ចុប្បន្ន", "Tune in planner": "កែសម្រួលគម្រោងដំណើរ", "AI to booking workflow": "ពីគម្រោងដំណើរទៅការកក់", "Plan your itinerary and review available booking options.": "រៀបចំគម្រោងដំណើរ និងពិនិត្យជម្រើសកក់ដែលមាន។", "Browse hotels for your trip": "ស្វែងរកសណ្ឋាគារសម្រាប់ដំណើររបស់អ្នក", "Need a place to stay?": "ត្រូវការកន្លែងស្នាក់នៅឬ?", "Browse hotels, resorts and guesthouses across Cambodia for your trip.": "ស្វែងរកសណ្ឋាគារ រមណីយដ្ឋាន និងផ្ទះសំណាក់ទូទាំងប្រទេសកម្ពុជា សម្រាប់ដំណើររបស់អ្នក។", "Frequently asked": "សំណួរញឹកញាប់", "Quick answers before you book": "ចម្លើយខ្លីៗមុនពេលកក់", "Open travel-bookings support": "ទាក់ទងជំនួយការកក់ដំណើរ", "Need a hand with a booking?": "ត្រូវការជំនួយក្នុងការកក់ឬ?", "Talk to our travel team about flights, changes, or refunds.": "ទាក់ទងក្រុមការងារទេសចរណ៍របស់យើងអំពីជើងហោះហើរ ការផ្លាស់ប្ដូរ ឬការសងប្រាក់។", "ZIVO. Flight prices powered by our partners (Duffel, Travelpayouts). Final price confirmed at checkout.": "ZIVO។ តម្លៃជើងហោះហើរផ្ដល់ដោយដៃគូ (Duffel, Travelpayouts)។ តម្លៃចុងក្រោយត្រូវបញ្ជាក់ពេលទូទាត់។", "Back to search": "ត្រឡប់ទៅការស្វែងរក", "Search": "ស្វែងរក",
  "Plan": "រៀបចំ", "AI picks the trip idea": "AI ជួយផ្ដល់គំនិតដំណើរ", "Prefill route + dates": "បំពេញផ្លូវ និងកាលបរិច្ឆេទ", "Compare": "ប្រៀបធៀប", "Review live partner fares": "ពិនិត្យតម្លៃបច្ចុប្បន្នពីដៃគូ", "Book": "កក់", "Continue through checkout": "បន្តទៅការទូទាត់", "Auto route": "ផ្លូវស្វ័យប្រវត្តិ", "Trip ideas": "គំនិតដំណើរ", "Plan your trip": "រៀបចំដំណើររបស់អ្នក", "More options": "ជម្រើសបន្ថែម", "Explore": "ស្វែងយល់", "500+ Airlines": "ក្រុមហ៊ុនអាកាសចរណ៍ជាង ៥០០", "Compare all major & low-cost carriers": "ប្រៀបធៀបក្រុមហ៊ុនអាកាសចរណ៍ធំៗ និងតម្លៃទាប", "Trusted Partners": "ដៃគូដែលទុកចិត្តបាន", "Book through licensed travel partners": "កក់តាមដៃគូទេសចរណ៍ដែលមានអាជ្ញាបណ្ណ", "Real-Time Prices": "តម្លៃបច្ចុប្បន្ន", "Live fares, always up to date": "ពិនិត្យតម្លៃពីលទ្ធផលបច្ចុប្បន្ន", "Booking support": "ជំនួយការកក់", "Contact the travel team": "ទាក់ទងក្រុមការងារទេសចរណ៍", "All routes": "ផ្លូវទាំងអស់", "From Phnom Penh": "ពីភ្នំពេញ", "From Siem Reap": "ពីសៀមរាប", "Cancellation terms": "លក្ខខណ្ឌលុបចោល", "Review fare rules": "ពិនិត្យលក្ខខណ្ឌតម្លៃ", "Booking confirmation": "ការបញ្ជាក់ការកក់", "Check provider confirmation": "ពិនិត្យការបញ្ជាក់ពីអ្នកផ្ដល់សេវា", "Transparent pricing": "តម្លៃច្បាស់លាស់", "All fees shown upfront": "ពិនិត្យថ្លៃសេវាមុនបញ្ជាក់", "My bookings": "ការកក់របស់ខ្ញុំ", "Manage trips & e-tickets": "គ្រប់គ្រងដំណើរ និងសំបុត្រអេឡិចត្រូនិក", "Flight status": "ស្ថានភាពជើងហោះហើរ", "Track live departures": "តាមដានការចេញដំណើរ", "Price alerts": "ការជូនដំណឹងតម្លៃ", "Get notified on drops": "ទទួលដំណឹងពេលតម្លៃធ្លាក់", "Support": "ជំនួយ", "About these prices": "អំពីតម្លៃទាំងនេះ", "Refund policy": "គោលការណ៍សងប្រាក់", "Cancellation": "ការលុបចោល", "Privacy": "ឯកជនភាព", "Terms": "លក្ខខណ្ឌ",
};

export function publicTravelText(value: string, language = document.documentElement.lang): string {
  if (language !== "km") return value;
  const key = value.trim();
  const translated = khmer[key];
  if (translated) return value.replace(key, translated);
  const budget = key.match(/^Under \$(\d+)$/);
  if (budget) return `ក្រោម ${budget[1]} USD`;
  for (const [pattern, prefix] of [[/^Increase (.+)$/, "បង្កើន"], [/^Decrease (.+)$/, "បន្ថយ"], [/^Open (.+)$/, "បើក"], [/^Search (.+)$/, "ស្វែងរក"], [/^Show hotels in (.+)$/, "បង្ហាញសណ្ឋាគារនៅ"]] as const) {
    const match = key.match(pattern);
    if (match) return `${prefix} ${publicTravelText(match[1], language)}`;
  }
  const recent = key.match(/^Remove (.+) from recent searches$/);
  if (recent) return `ដក ${recent[1]} ចេញពីការស្វែងរកថ្មីៗ`;
  if (key.startsWith("Selected: ")) return `បានជ្រើសរើស៖ ${key.slice(10)}`;
  if (key.startsWith("Depart: ")) return `ចេញដំណើរ៖ ${key.slice(8).replace("— tap return", "— ជ្រើសរើសថ្ងៃត្រឡប់")}`;
  return value;
}

export function TravelCopy({ text }: { text: string }) {
  const { locale } = useI18n();
  return <>{publicTravelText(text, locale)}</>;
}
