/** Global expansion — US + Cambodia */
import { COUNTRIES } from "@/config/internationalExpansion";

export function useGlobalExpansion() {
  return { countries: COUNTRIES, isLoading: false };
}

// Map language codes to their representative country flag SVG paths
const LANG_FLAG_MAP: Record<string, string> = {
  en: "/flags/us.svg",
  ar: "/flags/sa.svg",
  bg: "/flags/bg.svg",
  ca: "/flags/es.svg",
  zh: "/flags/cn.svg",
  kw: "/flags/gb.svg",
  hr: "/flags/hr.svg",
  cs: "/flags/cz.svg",
  da: "/flags/dk.svg",
  nl: "/flags/nl.svg",
  fi: "/flags/fi.svg",
  fr: "/flags/fr.svg",
  de: "/flags/de.svg",
  el: "/flags/gr.svg",
  he: "/flags/il.svg",
  hu: "/flags/hu.svg",
  is: "/flags/is.svg",
  id: "/flags/id.svg",
  it: "/flags/it.svg",
  ja: "/flags/jp.svg",
  km: "/flags/kh.svg",
  ko: "/flags/kr.svg",
  lt: "/flags/lt.svg",
  no: "/flags/no.svg",
  om: "/flags/et.svg",
  pl: "/flags/pl.svg",
  ro: "/flags/ro.svg",
  ru: "/flags/ru.svg",
  sr: "/flags/rs.svg",
  sk: "/flags/sk.svg",
  es: "/flags/es.svg",
  sv: "/flags/se.svg",
  th: "/flags/th.svg",
  tr: "/flags/tr.svg",
  uk: "/flags/ua.svg",
  vi: "/flags/vn.svg",
  pt: "/flags/pt.svg",
};

export function useSupportedLanguages(_enabled?: boolean) {
  return {
    data: [
      { code: "en", name: "English", native_name: "English", flag_emoji: "🇺🇸", flag_svg: LANG_FLAG_MAP["en"], is_active: true },
      { code: "ar", name: "Arabic", native_name: "العربية", flag_emoji: "🇸🇦", flag_svg: LANG_FLAG_MAP["ar"], is_active: true },
      { code: "bg", name: "Bulgarian", native_name: "Български", flag_emoji: "🇧🇬", flag_svg: LANG_FLAG_MAP["bg"], is_active: true },
      { code: "ca", name: "Catalan", native_name: "Català", flag_emoji: "🇪🇸", flag_svg: LANG_FLAG_MAP["ca"], is_active: true },
      { code: "zh", name: "Chinese (Simplified)", native_name: "简体中文", flag_emoji: "🇨🇳", flag_svg: LANG_FLAG_MAP["zh"], is_active: true },
      { code: "kw", name: "Cornish", native_name: "Kernewek", flag_emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flag_svg: LANG_FLAG_MAP["kw"], is_active: true },
      { code: "hr", name: "Croatian", native_name: "Hrvatski", flag_emoji: "🇭🇷", flag_svg: LANG_FLAG_MAP["hr"], is_active: true },
      { code: "cs", name: "Czech", native_name: "Čeština", flag_emoji: "🇨🇿", flag_svg: LANG_FLAG_MAP["cs"], is_active: true },
      { code: "da", name: "Danish", native_name: "Dansk", flag_emoji: "🇩🇰", flag_svg: LANG_FLAG_MAP["da"], is_active: true },
      { code: "nl", name: "Dutch", native_name: "Nederlands", flag_emoji: "🇳🇱", flag_svg: LANG_FLAG_MAP["nl"], is_active: true },
      { code: "fi", name: "Finnish", native_name: "Suomi", flag_emoji: "🇫🇮", flag_svg: LANG_FLAG_MAP["fi"], is_active: true },
      { code: "fr", name: "French", native_name: "Français", flag_emoji: "🇫🇷", flag_svg: LANG_FLAG_MAP["fr"], is_active: true },
      { code: "de", name: "German", native_name: "Deutsch", flag_emoji: "🇩🇪", flag_svg: LANG_FLAG_MAP["de"], is_active: true },
      { code: "el", name: "Greek", native_name: "Ελληνικά", flag_emoji: "🇬🇷", flag_svg: LANG_FLAG_MAP["el"], is_active: true },
      { code: "he", name: "Hebrew", native_name: "עברית", flag_emoji: "🇮🇱", flag_svg: LANG_FLAG_MAP["he"], is_active: true },
      { code: "hu", name: "Hungarian", native_name: "Magyar", flag_emoji: "🇭🇺", flag_svg: LANG_FLAG_MAP["hu"], is_active: true },
      { code: "is", name: "Icelandic", native_name: "Íslenska", flag_emoji: "🇮🇸", flag_svg: LANG_FLAG_MAP["is"], is_active: true },
      { code: "id", name: "Indonesian", native_name: "Bahasa Indonesia", flag_emoji: "🇮🇩", flag_svg: LANG_FLAG_MAP["id"], is_active: true },
      { code: "it", name: "Italian", native_name: "Italiano", flag_emoji: "🇮🇹", flag_svg: LANG_FLAG_MAP["it"], is_active: true },
      { code: "ja", name: "Japanese", native_name: "日本語", flag_emoji: "🇯🇵", flag_svg: LANG_FLAG_MAP["ja"], is_active: true },
      { code: "km", name: "Khmer", native_name: "ភាសាខ្មែរ", flag_emoji: "🇰🇭", flag_svg: LANG_FLAG_MAP["km"], is_active: true },
      { code: "ko", name: "Korean", native_name: "한국어", flag_emoji: "🇰🇷", flag_svg: LANG_FLAG_MAP["ko"], is_active: true },
      { code: "lt", name: "Lithuanian", native_name: "Lietuvių", flag_emoji: "🇱🇹", flag_svg: LANG_FLAG_MAP["lt"], is_active: true },
      { code: "no", name: "Norwegian", native_name: "Norsk", flag_emoji: "🇳🇴", flag_svg: LANG_FLAG_MAP["no"], is_active: true },
      { code: "om", name: "Oromo", native_name: "Afaan Oromoo", flag_emoji: "🇪🇹", flag_svg: LANG_FLAG_MAP["om"], is_active: true },
      { code: "pl", name: "Polish", native_name: "Polski", flag_emoji: "🇵🇱", flag_svg: LANG_FLAG_MAP["pl"], is_active: true },
      { code: "pt", name: "Portuguese", native_name: "Português", flag_emoji: "🇵🇹", flag_svg: LANG_FLAG_MAP["pt"], is_active: true },
      { code: "ro", name: "Romanian", native_name: "Română", flag_emoji: "🇷🇴", flag_svg: LANG_FLAG_MAP["ro"], is_active: true },
      { code: "ru", name: "Russian", native_name: "Русский", flag_emoji: "🇷🇺", flag_svg: LANG_FLAG_MAP["ru"], is_active: true },
      { code: "sr", name: "Serbian", native_name: "Српски", flag_emoji: "🇷🇸", flag_svg: LANG_FLAG_MAP["sr"], is_active: true },
      { code: "sk", name: "Slovak", native_name: "Slovenčina", flag_emoji: "🇸🇰", flag_svg: LANG_FLAG_MAP["sk"], is_active: true },
      { code: "es", name: "Spanish", native_name: "Español", flag_emoji: "🇪🇸", flag_svg: LANG_FLAG_MAP["es"], is_active: true },
      { code: "sv", name: "Swedish", native_name: "Svenska", flag_emoji: "🇸🇪", flag_svg: LANG_FLAG_MAP["sv"], is_active: true },
      { code: "th", name: "Thai", native_name: "ไทย", flag_emoji: "🇹🇭", flag_svg: LANG_FLAG_MAP["th"], is_active: true },
      { code: "tr", name: "Turkish", native_name: "Türkçe", flag_emoji: "🇹🇷", flag_svg: LANG_FLAG_MAP["tr"], is_active: true },
      { code: "uk", name: "Ukrainian", native_name: "Українська", flag_emoji: "🇺🇦", flag_svg: LANG_FLAG_MAP["uk"], is_active: true },
      { code: "vi", name: "Vietnamese", native_name: "Tiếng Việt", flag_emoji: "🇻🇳", flag_svg: LANG_FLAG_MAP["vi"], is_active: true },
    ],
    isLoading: false,
  };
}
