#!/usr/bin/env node
// Dedicated Review-only static build. Assembles ./dist from ./src + ./public and
// injects the FULL 40-char commit SHA + build timestamp. No bundler, no source maps,
// no secrets, no network. Output is what Cloudflare Pages publishes as the Review build.
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "src");
const PUBLIC = join(here, "public");
const DIST = join(here, "dist");

function git(cmd) { try { return execSync(`git ${cmd}`, { cwd: here }).toString().trim(); } catch { return ""; } }

// Full 40-char SHA: explicit override → Cloudflare's commit SHA (if full) → git HEAD.
let sha = process.env.REVIEW_SHA || process.env.CF_PAGES_COMMIT_SHA || git("rev-parse HEAD");
sha = String(sha).trim();
if (!/^[0-9a-f]{40}$/.test(sha)) {
  console.error(`FATAL: could not resolve a full 40-char SHA (got "${sha}"). Set REVIEW_SHA.`);
  process.exit(1);
}
// Deterministic build timestamp: override → the commit's committer date (reproducible).
const builtAt = process.env.REVIEW_BUILT || git("show -s --format=%cI HEAD") || new Date(0).toISOString();

// Fresh dist
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

// Injected, secret-free config.
writeFileSync(
  join(DIST, "config.js"),
  `/* generated by build.mjs — no secrets */\nwindow.__REVIEW__ = ${JSON.stringify({ environment: "Review", demoDataOnly: true, actionsDisabled: true, sha, builtAt })};\n`
);

// Copy static assets verbatim (html/css/js + 404.html).
for (const f of readdirSync(SRC)) copyFileSync(join(SRC, f), join(DIST, f));
// Copy Cloudflare Pages config (_headers, _redirects).
if (existsSync(PUBLIC)) for (const f of readdirSync(PUBLIC)) copyFileSync(join(PUBLIC, f), join(DIST, f));

// Guard: no source maps must ship.
const maps = readdirSync(DIST).filter((f) => f.endsWith(".map"));
if (maps.length) { console.error("FATAL: source maps in dist:", maps); process.exit(1); }

console.log("Review build OK");
console.log("  environment: Review · demo data only · actions disabled");
console.log("  sha:        ", sha, `(${sha.length} chars)`);
console.log("  builtAt:    ", builtAt);
console.log("  dist files: ", readdirSync(DIST).join(", "));
