export type LocalCopy = [string, string];
export interface CambodiaGuide { path: string; title: LocalCopy; intro: LocalCopy; planning: LocalCopy; hotelCity?: string; airport?: string; source: string }
const tourism = "https://www.tourismcambodia.org/provinces";
const techo = "https://www.techoairport.com.kh/news/airport-certification";
const angkor = "https://english.sai-airport.com/jcjj/38953.jhtml";
export const cambodiaGuides: CambodiaGuide[] = [
  { path: "/cambodia", title: ["Plan your Cambodia trip", "រៀបចំដំណើររបស់អ្នកនៅកម្ពុជា"], intro: ["Connect Phnom Penh, Siem Reap, Kampot, Sihanoukville and Battambang in a trip that fits your time. Use this hub to compare places to stay and plan each travel leg separately.", "រៀបចំដំណើរទៅភ្នំពេញ សៀមរាប កំពត ព្រះសីហនុ និងបាត់ដំបង តាមពេលវេលារបស់អ្នក។ ស្វែងរកកន្លែងស្នាក់នៅ និងរៀបចំការធ្វើដំណើរនីមួយៗ។"], planning: ["Start with your arrival city and departure date. Choose overnight stops before committing to connecting transport. Review the exact airport, property address, baggage allowance and cancellation terms in each booking; a guide is not a confirmation of availability.", "ចាប់ផ្ដើមពីទីក្រុងដែលអ្នកមកដល់ និងថ្ងៃចេញដំណើរ។ ជ្រើសរើសកន្លែងស្នាក់នៅ មុនពេលកក់ការធ្វើដំណើរបន្ត។ ពិនិត្យអាកាសយានដ្ឋាន អាសយដ្ឋាន កម្រិតឥវ៉ាន់ និងលក្ខខណ្ឌលុបចោល មុនបញ្ជាក់ការកក់។"], source: tourism },
  { path: "/cambodia/phnom-penh", title: ["Phnom Penh travel guide", "មគ្គុទ្ទេសក៍ដំណើរនៅភ្នំពេញ"], intro: ["Cambodia’s capital brings together the Royal Palace, museums and riverfront neighborhoods. Choose a hotel location around the places you want to visit, then plan local transport from its actual address.", "រាជធានីភ្នំពេញមានព្រះបរមរាជវាំង សារមន្ទីរ និងតំបន់មាត់ទន្លេ។ ជ្រើសរើសសណ្ឋាគារជិតកន្លែងដែលអ្នកចង់ទៅ ហើយរៀបចំការធ្វើដំណើរតាមអាសយដ្ឋានពិតប្រាកដ។"], planning: ["For current commercial flights, check Techo International Airport (KTI). Older itineraries may mention PNH. Compare the airport code on the airline confirmation with your transfer destination, and leave time between landing and onward travel.", "សម្រាប់ជើងហោះហើរពាណិជ្ជកម្មបច្ចុប្បន្ន សូមពិនិត្យអាកាសយានដ្ឋានអន្តរជាតិតេជោ (KTI)។ ឯកសារចាស់អាចបង្ហាញ PNH។ ផ្ទៀងផ្ទាត់លេខកូដលើការបញ្ជាក់របស់ក្រុមហ៊ុនអាកាសចរណ៍ និងទុកពេលសម្រាប់ដំណើរបន្ត។"], hotelCity: "Phnom Penh", airport: "KTI", source: "https://www.tourismcambodia.org/provinces/44/phnom-penh-capital-city" },
  { path: "/cambodia/siem-reap", title: ["Siem Reap travel guide", "មគ្គុទ្ទេសក៍ដំណើរនៅសៀមរាប"], intro: ["Siem Reap is a base for visiting Angkor and exploring the city. Separate your temple plans from your arrival day so that a flight delay does not force changes to a tightly timed itinerary.", "សៀមរាបជាកន្លែងស្នាក់នៅសម្រាប់ទស្សនាអង្គរ និងស្វែងយល់ពីទីក្រុង។ រៀបចំការទស្សនាប្រាសាទនៅថ្ងៃផ្សេងពីថ្ងៃមកដល់ ដើម្បីទុកពេលសម្រាប់ការពន្យារជើងហោះហើរ។"], planning: ["Check Siem Reap–Angkor International Airport (SAI) when booking flights and transfers. REP appears in older airport references. Confirm the transfer pickup point and your hotel’s check-in arrangements before arrival.", "ពិនិត្យអាកាសយានដ្ឋានអន្តរជាតិសៀមរាបអង្គរ (SAI) នៅពេលកក់ជើងហោះហើរ និងការទទួលដឹកជញ្ជូន។ REP ជាលេខកូដក្នុងឯកសារចាស់។ បញ្ជាក់កន្លែងទទួល និងពេលចូលស្នាក់នៅ មុនមកដល់។"], hotelCity: "Siem Reap", airport: "SAI", source: angkor },
  { path: "/cambodia/kampot", title: ["Kampot trip planning", "រៀបចំដំណើរទៅកំពត"], intro: ["Use Kampot as a stop on a southern Cambodia itinerary. Plan the town stay and any trips outside town separately, rather than assuming every activity is close to your accommodation.", "ជ្រើសរើសកំពតជាកន្លែងឈប់ស្នាក់នៅក្នុងដំណើរទៅភាគខាងត្បូងនៃកម្ពុជា។ រៀបចំការស្នាក់នៅក្នុងក្រុង និងដំណើរក្រៅក្រុងដាច់ដោយឡែក ដោយពិនិត្យចម្ងាយពីកន្លែងស្នាក់នៅ។"], planning: ["Compare the property’s map location, arrival instructions and transport arrangements. If arriving after a road journey, confirm late check-in with the property. Keep the next travel leg flexible until you have checked the actual departure point and schedule.", "ប្រៀបធៀបទីតាំងលើផែនទី ការណែនាំពេលមកដល់ និងមធ្យោបាយធ្វើដំណើរ។ ប្រសិនបើមកដល់យឺត សូមបញ្ជាក់ជាមួយកន្លែងស្នាក់នៅ។ ពិនិត្យចំណុចចេញដំណើរ និងកាលវិភាគសម្រាប់ដំណើរបន្ទាប់។"], hotelCity: "Kampot", source: tourism },
  { path: "/cambodia/sihanoukville", title: ["Sihanoukville and onward travel", "ព្រះសីហនុ និងដំណើរបន្ត"], intro: ["Sihanoukville connects a mainland stay with Cambodia’s coastal and island destinations. A mainland hotel, an island property and an airport transfer are different parts of the trip; check each location carefully.", "ក្រុងព្រះសីហនុភ្ជាប់ការស្នាក់នៅលើដីគោកជាមួយតំបន់ឆ្នេរ និងកោះ។ សណ្ឋាគារលើដីគោក កន្លែងស្នាក់នៅលើកោះ និងការដឹកជញ្ជូនពីអាកាសយានដ្ឋាន ជាផ្នែកដាច់ដោយឡែកនៃដំណើរ។"], planning: ["Sihanouk International Airport uses KOS. If continuing to an island, verify the ferry operator, pier and current departure time separately. Do not assume a flight or hotel booking includes a boat transfer.", "អាកាសយានដ្ឋានអន្តរជាតិព្រះសីហនុប្រើលេខកូដ KOS។ ប្រសិនបើបន្តទៅកោះ សូមពិនិត្យក្រុមហ៊ុនទូក កំពង់ផែ និងម៉ោងចេញដំណើរ។ ការកក់ជើងហោះហើរ ឬសណ្ឋាគារ មិនមានន័យថារួមបញ្ចូលទូកទេ។"], hotelCity: "Sihanoukville", airport: "KOS", source: "https://kos.cambodia-airports.aero/" },
  { path: "/cambodia/battambang", title: ["Battambang trip planning", "រៀបចំដំណើរទៅបាត់ដំបង"], intro: ["Add Battambang to a Cambodia itinerary when you want time in a provincial city as well as the major arrival hubs. Choose a city base first, then arrange visits outside the center around your available time.", "បន្ថែមបាត់ដំបងក្នុងគម្រោងដំណើរ ប្រសិនបើអ្នកចង់ស្នាក់នៅក្នុងទីក្រុងខេត្ត។ ជ្រើសរើសកន្លែងស្នាក់នៅក្នុងក្រុងជាមុន រួចរៀបចំដំណើរក្រៅក្រុងតាមពេលវេលារបស់អ្នក។"], planning: ["Check road transport departure and arrival points before choosing a hotel. Compare room occupancy, cancellation terms and the property’s contact instructions. This guide does not advertise scheduled passenger flights to Battambang.", "ពិនិត្យទីតាំងចេញដំណើរ និងមកដល់នៃការដឹកជញ្ជូនផ្លូវគោក មុនជ្រើសរើសសណ្ឋាគារ។ ប្រៀបធៀបចំនួនភ្ញៀវ លក្ខខណ្ឌលុបចោល និងការទាក់ទង។ មគ្គុទ្ទេសក៍នេះមិនផ្សព្វផ្សាយជើងហោះហើរដឹកអ្នកដំណើរទៅបាត់ដំបងទេ។"], hotelCity: "Battambang", source: tourism },
  { path: "/flights/phnom-penh-siem-reap", title: ["Phnom Penh to Siem Reap: plan your flight", "ភ្នំពេញទៅសៀមរាប៖ រៀបចំជើងហោះហើរ"], intro: ["Use KTI for Phnom Penh’s Techo airport and SAI for Siem Reap–Angkor when planning this journey. Open the search form, choose your travel dates and travelers, and compare the returned options.", "ប្រើ KTI សម្រាប់អាកាសយានដ្ឋានតេជោ និង SAI សម្រាប់សៀមរាបអង្គរ។ បើកទម្រង់ស្វែងរក ជ្រើសរើសថ្ងៃធ្វើដំណើរ និងចំនួនអ្នកដំណើរ រួចប្រៀបធៀបជម្រើសដែលបង្ហាញ។"], planning: ["This route guide does not promise a direct flight, a daily service or a fixed fare. Compare the total itinerary, baggage and cancellation terms in the actual results. Allow for airport transfers at both ends when comparing flying with a road journey.", "មគ្គុទ្ទេសក៍នេះមិនធានាជើងហោះហើរត្រង់ សេវាប្រចាំថ្ងៃ ឬតម្លៃថេរទេ។ ប្រៀបធៀបដំណើរទាំងមូល ឥវ៉ាន់ និងលក្ខខណ្ឌលុបចោលក្នុងលទ្ធផលពិតប្រាកដ។ គិតបញ្ចូលពេលធ្វើដំណើរទៅនិងពីអាកាសយានដ្ឋានផងដែរ។"], hotelCity: "Siem Reap", airport: "SAI", source: angkor },
];
for (const [code, current, en, km, source] of [
  ["kti", "KTI", "Techo International Airport", "អាកាសយានដ្ឋានអន្តរជាតិតេជោ", techo],
  ["pnh", "KTI", "PNH: legacy Phnom Penh airport reference", "PNH៖ លេខកូដអាកាសយានដ្ឋានភ្នំពេញចាស់", techo],
  ["sai", "SAI", "Siem Reap–Angkor International Airport", "អាកាសយានដ្ឋានអន្តរជាតិសៀមរាបអង្គរ", angkor],
  ["rep", "SAI", "REP: legacy Siem Reap airport reference", "REP៖ លេខកូដអាកាសយានដ្ឋានសៀមរាបចាស់", angkor],
  ["kos", "KOS", "Sihanouk International Airport", "អាកាសយានដ្ឋានអន្តរជាតិព្រះសីហនុ", "https://kos.cambodia-airports.aero/"],
]) cambodiaGuides.push({ path: `/airports/${code}`, title: [en, km], airport: current, source,
  intro: [`For current travel planning, use airport code ${current}. Check the airport name and code on your airline confirmation before arranging a transfer. Older references may use a different airport for the same city.`, `សម្រាប់ការរៀបចំដំណើរបច្ចុប្បន្ន ប្រើលេខកូដ ${current}។ ពិនិត្យឈ្មោះ និងលេខកូដអាកាសយានដ្ឋានលើការបញ្ជាក់របស់ក្រុមហ៊ុនអាកាសចរណ៍ មុនរៀបចំការទទួលដឹកជញ្ជូន។`],
  planning: ["Use the official airport website for current arrivals, departures and passenger information. Keep your airline’s baggage and check-in instructions with your booking. Search results, not this guide, determine available flights and fares.", "ប្រើគេហទំព័រផ្លូវការរបស់អាកាសយានដ្ឋាន ដើម្បីពិនិត្យជើងហោះហើរមកដល់ ចេញដំណើរ និងព័ត៌មានអ្នកដំណើរ។ រក្សាការណែនាំអំពីឥវ៉ាន់ និងការចុះឈ្មោះរបស់ក្រុមហ៊ុនអាកាសចរណ៍ជាមួយការកក់របស់អ្នក។"],
});
export const cambodiaGuidePaths = cambodiaGuides.map(guide => guide.path);
export const travelFaqs: { question: LocalCopy; answer: LocalCopy }[] = [
  { question: ["Where can I check current prices?", "តើខ្ញុំអាចពិនិត្យតម្លៃបច្ចុប្បន្ននៅឯណា?"], answer: ["Choose your dates and travelers in the flight or hotel search. Review the returned price, inclusions and cancellation terms before confirming.", "ជ្រើសរើសកាលបរិច្ឆេទ និងចំនួនអ្នកដំណើរក្នុងការស្វែងរកជើងហោះហើរ ឬសណ្ឋាគារ។ ពិនិត្យតម្លៃ សេវារួមបញ្ចូល និងលក្ខខណ្ឌលុបចោល មុនបញ្ជាក់។"] },
  { question: ["Does reading a guide make a booking?", "តើការអានមគ្គុទ្ទេសក៍ជាការកក់ឬ?"], answer: ["No. Guides help you plan. A booking requires choosing an available option, reviewing its terms and completing the confirmation flow.", "ទេ។ មគ្គុទ្ទេសក៍ជួយអ្នករៀបចំផែនការ។ ការកក់ត្រូវការជ្រើសរើសជម្រើសដែលមាន ពិនិត្យលក្ខខណ្ឌ និងបំពេញដំណើរការបញ្ជាក់។"] },
];
