#!/usr/bin/env node
import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {
  checkNativeWebSync,
  parsePlatforms,
} from "./check-web-sync.mjs";

async function withFixture(run) {
  const root = await mkdtemp(path.join(os.tmpdir(), "zivo-native-web-sync-"));
  try {
    await run(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

async function writeFiles(root, files) {
  await Promise.all(
    Object.entries(files).map(async ([relativePath, contents]) => {
      const target = path.join(root, relativePath);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, contents);
    }),
  );
}

test("native web sync checker accepts matching Capacitor payloads", async () => {
  await withFixture(async (root) => {
    await writeFiles(root, {
      "dist/index.html": "current index",
      "dist/assets/app.js": "current app",
      "android/app/src/main/assets/public/index.html": "current index",
      "android/app/src/main/assets/public/assets/app.js": "current app",
      "android/app/src/main/assets/public/cordova.js": "generated by Capacitor",
      "android/app/src/main/assets/public/cordova_plugins.js":
        "generated by Capacitor",
      "ios/App/App/public/index.html": "current index",
      "ios/App/App/public/assets/app.js": "current app",
      "ios/App/App/public/cordova.js": "generated by Capacitor",
      "ios/App/App/public/cordova_plugins.js": "generated by Capacitor",
    });

    const checks = await checkNativeWebSync({
      repoRoot: root,
      platforms: ["android", "ios"],
    });

    assert.deepEqual(
      checks.map((check) => check.platform),
      ["android", "ios"],
    );
    assert.equal(checks.every((check) => check.inSync), true);
    assert.deepEqual(
      checks.map((check) => check.sourceFileCount),
      [2, 2],
    );
    assert.deepEqual(
      checks.map((check) => check.nativeFileCount),
      [2, 2],
    );
  });
});

test("native web sync checker accepts an archived iOS payload override", async () => {
  await withFixture(async (root) => {
    const archiveRoot = path.join(
      root,
      "build/App.xcarchive/Products/Applications/App.app/public",
    );
    await writeFiles(root, {
      "dist/index.html": "current index",
      "dist/assets/app.js": "current app",
      "build/App.xcarchive/Products/Applications/App.app/public/index.html":
        "current index",
      "build/App.xcarchive/Products/Applications/App.app/public/assets/app.js":
        "current app",
      "build/App.xcarchive/Products/Applications/App.app/public/cordova.js":
        "generated by Capacitor",
    });

    const [check] = await checkNativeWebSync({
      repoRoot: root,
      platforms: ["ios"],
      nativeRoots: { ios: archiveRoot },
    });

    assert.equal(check.inSync, true);
    assert.equal(check.sourceFileCount, 2);
    assert.equal(check.nativeFileCount, 2);
  });
});

test("native web sync checker reports missing, unexpected, and changed files", async () => {
  await withFixture(async (root) => {
    await writeFiles(root, {
      "dist/index.html": "current index",
      "dist/assets/current.js": "current app",
      "android/app/src/main/assets/public/index.html": "stale index",
      "android/app/src/main/assets/public/assets/old.js": "old app",
    });

    const [check] = await checkNativeWebSync({
      repoRoot: root,
      platforms: ["android"],
    });

    assert.equal(check.inSync, false);
    assert.deepEqual(check.missingFromNative, ["assets/current.js"]);
    assert.deepEqual(check.unexpectedInNative, ["assets/old.js"]);
    assert.deepEqual(check.changed, ["index.html"]);
  });
});

test("native web sync checker accepts supported platform arguments only", () => {
  assert.deepEqual(parsePlatforms(), ["android", "ios"]);
  assert.deepEqual(
    parsePlatforms([
      "--platform=ios",
      "--platform",
      "android",
      "--platform",
      "ios",
    ]),
    ["ios", "android"],
  );
  assert.throws(
    () => parsePlatforms(["--platform", "web"]),
    /Unsupported platform: web/,
  );
  assert.throws(
    () => parsePlatforms(["--platform"]),
    /Missing platform value/,
  );
});
