#!/usr/bin/env node
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  cp,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {
  assertIosPrivacyManifestProjectWiring,
  collectIosReleaseCandidateFindings,
  collectPrivacyManifestFindings,
  inspectIosSourceRelease,
  parseIosProjectIdentity,
  validateIosArchive,
  validateIosIpa,
} from "../upload-to-app-store.mjs";

const repoRoot = path.resolve(new URL("../..", import.meta.url).pathname);
const projectPath = path.join(
  repoRoot,
  "ios/App/App.xcodeproj/project.pbxproj",
);
const manifestPath = path.join(repoRoot, "ios/App/App/PrivacyInfo.xcprivacy");

async function withFixture(run) {
  const root = await mkdtemp(path.join(os.tmpdir(), "zivo-ios-store-release-"));
  try {
    await run(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

async function writeFixtureFile(root, relativePath, contents) {
  const target = path.join(root, relativePath);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, contents);
  return target;
}

function appInfoPlist({ build = "5" } = {}) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>com.hizovo.app</string>
  <key>CFBundleShortVersionString</key>
  <string>1.3.0</string>
  <key>CFBundleVersion</key>
  <string>${build}</string>
</dict>
</plist>
`;
}

async function prepareRepoFixture(root) {
  await Promise.all([
    cp(projectPath, path.join(root, "ios/App/App.xcodeproj/project.pbxproj"), {
      recursive: false,
    }).catch(async () => {
      await mkdir(path.join(root, "ios/App/App.xcodeproj"), { recursive: true });
      await cp(
        projectPath,
        path.join(root, "ios/App/App.xcodeproj/project.pbxproj"),
      );
    }),
    cp(manifestPath, path.join(root, "ios/App/App/PrivacyInfo.xcprivacy"), {
      recursive: false,
    }).catch(async () => {
      await mkdir(path.join(root, "ios/App/App"), { recursive: true });
      await cp(
        manifestPath,
        path.join(root, "ios/App/App/PrivacyInfo.xcprivacy"),
      );
    }),
    writeFixtureFile(root, "dist/index.html", "current web payload"),
  ]);
}

async function prepareAppBundle(
  root,
  appPath,
  { includeRootManifest = true, build = "5", web = "current web payload" } = {},
) {
  await Promise.all([
    writeFixtureFile(root, path.relative(root, path.join(appPath, "Info.plist")), appInfoPlist({ build })),
    writeFixtureFile(root, path.relative(root, path.join(appPath, "public/index.html")), web),
    writeFixtureFile(
      root,
      path.relative(root, path.join(appPath, "public/cordova.js")),
      "generated by Capacitor",
    ),
  ]);
  if (includeRootManifest) {
    await cp(manifestPath, path.join(appPath, "PrivacyInfo.xcprivacy"));
  }
}

test("parses the App Release identity and verifies privacy-manifest target wiring", async () => {
  const project = await readFile(projectPath, "utf8");
  assert.deepEqual(parseIosProjectIdentity(project), {
    bundleIdentifier: "com.hizovo.app",
    marketingVersion: "1.3.0",
    buildNumber: "5",
  });
  const wiring = assertIosPrivacyManifestProjectWiring(project);
  assert.equal(wiring.fileReferenceId.length, 24);
  assert.equal(wiring.resourceBuildFileId.length, 24);

  const source = inspectIosSourceRelease({ repoRoot });
  assert.deepEqual(collectPrivacyManifestFindings(source.privacyManifest), []);
});

test("rejects a project where the manifest is not in the App Resources phase", async () => {
  const project = await readFile(projectPath, "utf8");
  const withoutResourceMembership = project.replace(
    /^\s*[A-F0-9]{24} \/\* PrivacyInfo\.xcprivacy in Resources \*\/,$/m,
    "",
  );
  assert.throws(
    () => assertIosPrivacyManifestProjectWiring(withoutResourceMembership),
    /must be included in the App target Resources build phase/,
  );
});

test("privacy evidence rejects tracking and missing advertised content types", () => {
  const privacyManifest = {
    NSPrivacyTracking: true,
    NSPrivacyTrackingDomains: ["tracking.example"],
    NSPrivacyCollectedDataTypes: [
      {
        NSPrivacyCollectedDataType: "NSPrivacyCollectedDataTypePhotosorVideos",
        NSPrivacyCollectedDataTypeLinked: true,
        NSPrivacyCollectedDataTypeTracking: true,
        NSPrivacyCollectedDataTypePurposes: [
          "NSPrivacyCollectedDataTypePurposeThirdPartyAdvertising",
        ],
      },
    ],
  };
  assert.match(
    collectPrivacyManifestFindings(privacyManifest).join("; "),
    /NSPrivacyTracking must be false.*NSPrivacyTrackingDomains must be an empty array.*must not be declared for tracking.*third-party advertising.*EmailsOrTextMessages is missing.*AudioData is missing.*OtherUserContent is missing/,
  );
});

test("candidate evidence rejects stale versions, missing app-root privacy, and stale web payload", () => {
  const findings = collectIosReleaseCandidateFindings({
    expectedIdentity: {
      bundleIdentifier: "com.hizovo.app",
      marketingVersion: "1.3.0",
      buildNumber: "5",
    },
    appIdentity: {
      bundleIdentifier: "com.hizovo.app",
      marketingVersion: "1.3.0",
      buildNumber: "4",
    },
    manifestPresent: false,
    manifestMatchesSource: false,
    privacyManifest: null,
    webCheck: {
      inSync: false,
      missingFromNative: ["assets/current.js"],
      unexpectedInNative: ["assets/old.js"],
      changed: ["index.html"],
    },
  });
  assert.match(
    findings.join("; "),
    /CFBundleVersion mismatch.*app bundle root is missing PrivacyInfo\.xcprivacy.*app bundle public payload does not match current dist/,
  );
});

test("accepts an archive only when the current manifest reaches the app root", async () => {
  await withFixture(async (root) => {
    await prepareRepoFixture(root);
    const appPath = path.join(
      root,
      "ios/build/zivosmedia.xcarchive/Products/Applications/App.app",
    );
    await prepareAppBundle(root, appPath);

    const result = await validateIosArchive({
      repoRoot: root,
      archivePath: path.join(root, "ios/build/zivosmedia.xcarchive"),
    });
    assert.equal(result.identity.buildNumber, "5");
    assert.equal(
      result.privacyManifestPath,
      path.join(appPath, "PrivacyInfo.xcprivacy"),
    );
  });
});

test("rejects an archive with only a nested or absent privacy manifest", async () => {
  await withFixture(async (root) => {
    await prepareRepoFixture(root);
    const archivePath = path.join(root, "ios/build/zivosmedia.xcarchive");
    const appPath = path.join(
      archivePath,
      "Products/Applications/App.app",
    );
    await prepareAppBundle(root, appPath, { includeRootManifest: false });
    await cp(
      manifestPath,
      path.join(appPath, "Frameworks/Example.framework/PrivacyInfo.xcprivacy"),
    ).catch(async () => {
      await mkdir(path.join(appPath, "Frameworks/Example.framework"), {
        recursive: true,
      });
      await cp(
        manifestPath,
        path.join(appPath, "Frameworks/Example.framework/PrivacyInfo.xcprivacy"),
      );
    });

    await assert.rejects(
      validateIosArchive({ repoRoot: root, archivePath }),
      /app bundle root is missing PrivacyInfo\.xcprivacy/,
    );
  });
});

test("upload validation rejects a stale synthetic IPA before any upload tool runs", async () => {
  await withFixture(async (root) => {
    await prepareRepoFixture(root);
    const stagingRoot = path.join(root, "staging");
    const appPath = path.join(stagingRoot, "Payload/App.app");
    await prepareAppBundle(root, appPath, { build: "4" });
    const ipaPath = path.join(root, "App.ipa");
    const zipped = spawnSync(
      "/usr/bin/zip",
      ["-qry", ipaPath, "Payload"],
      { cwd: stagingRoot, encoding: "utf8" },
    );
    assert.equal(zipped.status, 0, zipped.stderr || zipped.stdout);

    await assert.rejects(
      validateIosIpa({ repoRoot: root, ipaPath, temporaryRoot: root }),
      /CFBundleVersion mismatch \(expected 5, got 4\)/,
    );
  });
});
