-- Data API grants for post-2026 Supabase table exposure behavior.
-- RLS policies still decide which rows each role can read or mutate.
grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on table public.store_payment_settings to authenticated;
grant select, insert, update, delete on table public.salon_services to authenticated;
grant select, insert, update, delete on table public.salon_stylists to authenticated;
grant select, insert, update, delete on table public.salon_stylist_services to authenticated;
grant select, insert, update, delete on table public.salon_clients to authenticated;
grant select, insert, update, delete on table public.salon_bookings to authenticated;
grant select, insert, update, delete on table public.salon_expenses to authenticated;
grant select, insert, update, delete on table public.salon_waitlist to authenticated;
grant select, insert, update, delete on table public.salon_stylist_schedules to authenticated;
grant select, insert, update, delete on table public.salon_packages to authenticated;
grant select, insert, update, delete on table public.salon_package_services to authenticated;
grant select, insert, update, delete on table public.salon_retail_products to authenticated;
grant select, insert, update, delete on table public.salon_loyalty_settings to authenticated;
grant select, insert, update, delete on table public.salon_loyalty_events to authenticated;
grant select, insert, update, delete on table public.salon_reviews to authenticated;
grant select, insert, update, delete on table public.salon_booking_retail_items to authenticated;
grant select, insert, update, delete on table public.salon_blockouts to authenticated;
grant select, insert, update, delete on table public.salon_store_closures to authenticated;
grant select, insert, update, delete on table public.salon_gift_cards to authenticated;
grant select, insert, update, delete on table public.salon_gift_card_redemptions to authenticated;
grant select, insert, update, delete on table public.salon_time_entries to authenticated;
grant select, insert, update, delete on table public.salon_booking_addons to authenticated;
grant select, insert, update, delete on table public.salon_commission_payouts to authenticated;
grant select, insert, update, delete on table public.salon_reminder_settings to authenticated;
grant select, insert, update, delete on table public.salon_reminders to authenticated;
grant select, insert, update, delete on table public.salon_notification_template_overrides to authenticated;
grant select, insert, update, delete on table public.salon_sms_inbound_log to authenticated;
grant select, insert, update, delete on table public.salon_campaigns to authenticated;
grant select, insert, update, delete on table public.salon_campaign_recipients to authenticated;
grant select, insert, update, delete on table public.cafe_categories to authenticated;
grant select, insert, update, delete on table public.cafe_menu_items to authenticated;
grant select, insert, update, delete on table public.cafe_modifier_groups to authenticated;
grant select, insert, update, delete on table public.cafe_modifiers to authenticated;
grant select, insert, update, delete on table public.cafe_menu_item_modifier_groups to authenticated;
grant select, insert, update, delete on table public.cafe_tables to authenticated;
grant select, insert, update, delete on table public.cafe_orders to authenticated;
grant select, insert, update, delete on table public.cafe_order_items to authenticated;
grant select, insert, update, delete on table public.cafe_order_item_modifiers to authenticated;
grant select, insert, update, delete on table public.cafe_payments to authenticated;
grant select, insert, update, delete on table public.cafe_gift_cards to authenticated;
grant select, insert, update, delete on table public.cafe_gift_card_redemptions to authenticated;
grant select, insert, update, delete on table public.cafe_expenses to authenticated;
grant select, insert, update, delete on table public.cafe_baristas to authenticated;
grant select, insert, update, delete on table public.cafe_time_entries to authenticated;
grant select, insert, update, delete on table public.cafe_reviews to authenticated;
grant select, insert, update, delete on table public.cafe_promotions to authenticated;
grant select, insert, update, delete on table public.cafe_inventory_items to authenticated;
grant select, insert, update, delete on table public.cafe_recipes to authenticated;
grant select, insert, update, delete on table public.cafe_inventory_movements to authenticated;
grant select, insert, update, delete on table public.cafe_suppliers to authenticated;
grant select, insert, update, delete on table public.cafe_purchase_orders to authenticated;
grant select, insert, update, delete on table public.cafe_purchase_order_items to authenticated;
grant select, insert, update, delete on table public.cafe_loyalty_programs to authenticated;
grant select, insert, update, delete on table public.cafe_loyalty_balances to authenticated;
grant select, insert, update, delete on table public.cafe_loyalty_events to authenticated;
grant select, insert, update, delete on table public.cafe_shifts to authenticated;
grant select, insert, update, delete on table public.cafe_hours to authenticated;
grant select, insert, update, delete on table public.cafe_settings to authenticated;
grant select, insert, update, delete on table public.cafe_till_sessions to authenticated;
grant select, insert, update, delete on table public.car_rental_locations to authenticated;
grant select, insert, update, delete on table public.car_rental_vehicles to authenticated;
grant select, insert, update, delete on table public.car_rental_addons to authenticated;
grant select, insert, update, delete on table public.car_rental_customers to authenticated;
grant select, insert, update, delete on table public.car_rental_reservation_addons to authenticated;
grant select, insert, update, delete on table public.cafe_till_drops to authenticated;
grant select, insert, update, delete on table public.car_rental_expenses to authenticated;
grant select, insert, update, delete on table public.car_rental_maintenance to authenticated;
grant select, insert, update, delete on table public.car_rental_promotions to authenticated;
grant select, insert, update, delete on table public.car_rental_promo_redemptions to authenticated;
grant select, insert, update, delete on table public.cafe_tip_payouts to authenticated;
grant select, insert, update, delete on table public.cafe_tip_payout_lines to authenticated;
grant select, insert, update, delete on table public.car_rental_vehicle_blackouts to authenticated;
grant select, insert, update, delete on table public.cafe_reservations to authenticated;
grant select, insert, update, delete on table public.cafe_customer_notes to authenticated;
grant select, insert, update, delete on table public.car_dealership_vehicles to authenticated;
grant select, insert, update, delete on table public.car_dealership_customers to authenticated;
grant select, insert, update, delete on table public.car_dealership_leads to authenticated;
grant select, insert, update, delete on table public.car_dealership_test_drives to authenticated;
grant select, insert, update, delete on table public.car_dealership_sales to authenticated;
grant select, insert, update, delete on table public.car_dealership_trade_ins to authenticated;
grant select, insert, update, delete on table public.car_dealership_financing to authenticated;
grant select, insert, update, delete on table public.car_dealership_lead_activities to authenticated;
grant select, insert, update, delete on table public.car_dealership_expenses to authenticated;
grant select, insert, update, delete on table public.car_dealership_reviews to authenticated;
grant select, insert, update, delete on table public.car_dealership_promotions to authenticated;
grant select, insert, update, delete on table public.car_dealership_customer_interactions to authenticated;
grant select, insert, update, delete on table public.cafe_bundles to authenticated;
grant select, insert, update, delete on table public.cafe_bundle_items to authenticated;
grant select, insert, update, delete on table public.car_dealership_deal_documents to authenticated;
grant select, insert, update, delete on table public.cafe_order_item_voids to authenticated;
grant select, insert, update, delete on table public.car_rental_reservation_events to authenticated;
grant select, insert, update, delete on table public.car_rental_payment_attempts to authenticated;
grant select, insert, update, delete on table public.car_rental_stripe_webhook_events to authenticated;
grant select, insert, update, delete on table public.ar_loaner_vehicles to authenticated;
grant select, insert, update, delete on table public.ar_job_photos to authenticated;
grant select, insert, update, delete on table public.ar_labor_entries to authenticated;
grant select, insert, update, delete on table public.store_promotions to authenticated;
grant select, insert, update, delete on table public.store_reviews to authenticated;
grant select, insert, update, delete on table public.store_messages to authenticated;
grant select, insert, update, delete on table public.salon_booking_series to authenticated;
grant select, insert, update, delete on table public.ppv_posts to authenticated;
grant select, insert, update, delete on table public.ppv_unlocks to authenticated;
grant select, insert, update, delete on table public.direct_message_unlocks to authenticated;
grant select, insert, update, delete on table public.direct_message_locked_payloads to authenticated;
grant select, insert, update, delete on table public.content_reports to authenticated;
grant select, insert, update, delete on table public.ar_shop_settings to authenticated;
grant select, insert, update, delete on table public.ar_doc_counters to authenticated;
grant select, insert, update, delete on table public.salon_booking_payments to authenticated;
grant select, insert, update, delete on table public.salon_color_formulas to authenticated;
grant select, insert, update, delete on table public.salon_membership_tiers to authenticated;
grant select, insert, update, delete on table public.salon_client_memberships to authenticated;

grant select on table public.cafe_bundle_items to anon;
grant select on table public.cafe_bundles to anon;
grant select on table public.cafe_categories to anon;
grant select on table public.cafe_hours to anon;
grant select on table public.cafe_loyalty_programs to anon;
grant select on table public.cafe_menu_item_modifier_groups to anon;
grant select on table public.cafe_menu_items to anon;
grant select on table public.cafe_modifier_groups to anon;
grant select on table public.cafe_modifiers to anon;
grant select on table public.cafe_reviews to anon;
grant select on table public.cafe_settings to anon;
grant select on table public.cafe_tables to anon;
grant select on table public.car_dealership_leads to anon;
grant select on table public.car_dealership_promotions to anon;
grant select on table public.car_dealership_reviews to anon;
grant select on table public.car_dealership_vehicles to anon;
grant select on table public.car_rental_addons to anon;
grant select on table public.car_rental_customers to anon;
grant select on table public.car_rental_locations to anon;
grant select on table public.car_rental_promotions to anon;
grant select on table public.car_rental_reservation_addons to anon;
grant select on table public.car_rental_reservations to anon;
grant select on table public.car_rental_reviews to anon;
grant select on table public.car_rental_store_settings to anon;
grant select on table public.car_rental_vehicle_blackouts to anon;
grant select on table public.car_rental_vehicles to anon;
grant select on table public.salon_bookings to anon;
grant select on table public.salon_reviews to anon;
grant select on table public.salon_services to anon;
grant select on table public.salon_stylist_schedules to anon;
grant select on table public.salon_stylist_services to anon;
grant select on table public.salon_stylists to anon;

grant insert on table public.car_dealership_leads to anon;
grant insert on table public.car_dealership_reviews to anon;
grant insert on table public.car_rental_customers to anon;
grant insert on table public.car_rental_promo_redemptions to anon;
grant insert on table public.car_rental_reservation_addons to anon;
grant insert on table public.car_rental_reviews to anon;
grant insert on table public.salon_bookings to anon;

grant update on table public.car_dealership_reviews to anon;
grant update on table public.car_rental_reservations to anon;
