-- Store-credit gift cards. The owner issues a card with a unique code and
-- an initial balance; redemptions are recorded in a separate ledger table
-- so we can audit every spend. A trigger keeps salon_gift_cards.balance_cents
-- in sync with the sum of its redemptions, so the UI only inserts a row
-- with the spend amount and reads balance_cents back.

CREATE TABLE IF NOT EXISTS public.salon_gift_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id UUID NOT NULL REFERENCES public.store_profiles(id) ON DELETE CASCADE,
  -- 12-char alphanumeric in 3 groups of 4 (XXXX-XXXX-XXXX). Stored as
  -- generated by the client to keep the surface area small.
  code TEXT NOT NULL CHECK (char_length(code) BETWEEN 12 AND 16),
  initial_cents INTEGER NOT NULL CHECK (initial_cents >= 0),
  balance_cents INTEGER NOT NULL CHECK (balance_cents >= 0),
  recipient_name TEXT CHECK (recipient_name IS NULL OR char_length(recipient_name) <= 120),
  recipient_email TEXT CHECK (recipient_email IS NULL OR char_length(recipient_email) <= 160),
  recipient_phone TEXT CHECK (recipient_phone IS NULL OR char_length(recipient_phone) <= 40),
  purchaser_name TEXT CHECK (purchaser_name IS NULL OR char_length(purchaser_name) <= 120),
  message TEXT CHECK (message IS NULL OR char_length(message) <= 500),
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT true,
  issued_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS salon_gift_cards_code_uidx
  ON public.salon_gift_cards (code);
CREATE INDEX IF NOT EXISTS salon_gift_cards_store_idx
  ON public.salon_gift_cards (store_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.salon_gift_card_redemptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gift_card_id UUID NOT NULL REFERENCES public.salon_gift_cards(id) ON DELETE CASCADE,
  store_id UUID NOT NULL REFERENCES public.store_profiles(id) ON DELETE CASCADE,
  booking_id UUID REFERENCES public.salon_bookings(id) ON DELETE SET NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  notes TEXT CHECK (notes IS NULL OR char_length(notes) <= 500),
  redeemed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  redeemed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS salon_gift_card_redemptions_card_idx
  ON public.salon_gift_card_redemptions (gift_card_id, redeemed_at DESC);
CREATE INDEX IF NOT EXISTS salon_gift_card_redemptions_store_idx
  ON public.salon_gift_card_redemptions (store_id, redeemed_at DESC);

DROP TRIGGER IF EXISTS salon_gift_cards_set_updated_at ON public.salon_gift_cards;
CREATE TRIGGER salon_gift_cards_set_updated_at
  BEFORE UPDATE ON public.salon_gift_cards
  FOR EACH ROW EXECUTE FUNCTION public.tg_salon_set_updated_at_generic();

-- Apply a redemption to the card's balance. Locks the card row to avoid
-- racing concurrent redemptions, refuses to over-spend, and refuses to
-- redeem against an inactive or expired card.
CREATE OR REPLACE FUNCTION public.tg_salon_gift_card_apply_redemption()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_balance INTEGER;
  v_active BOOLEAN;
  v_expires TIMESTAMPTZ;
BEGIN
  SELECT balance_cents, is_active, expires_at
    INTO v_balance, v_active, v_expires
    FROM public.salon_gift_cards
    WHERE id = NEW.gift_card_id
    FOR UPDATE;

  IF v_balance IS NULL THEN
    RAISE EXCEPTION 'Gift card not found.' USING ERRCODE = 'P0002';
  END IF;
  IF NOT v_active THEN
    RAISE EXCEPTION 'Gift card is disabled.' USING ERRCODE = '22023';
  END IF;
  IF v_expires IS NOT NULL AND v_expires < now() THEN
    RAISE EXCEPTION 'Gift card has expired.' USING ERRCODE = '22023';
  END IF;
  IF NEW.amount_cents > v_balance THEN
    RAISE EXCEPTION 'Redemption exceeds the remaining balance ($%).', (v_balance / 100.0)
      USING ERRCODE = '22023';
  END IF;

  UPDATE public.salon_gift_cards
    SET balance_cents = balance_cents - NEW.amount_cents,
        updated_at = now()
    WHERE id = NEW.gift_card_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS salon_gift_card_redemptions_apply ON public.salon_gift_card_redemptions;
CREATE TRIGGER salon_gift_card_redemptions_apply
  BEFORE INSERT ON public.salon_gift_card_redemptions
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_salon_gift_card_apply_redemption();

-- If a redemption is deleted (refund / mistake), put the balance back.
CREATE OR REPLACE FUNCTION public.tg_salon_gift_card_revert_redemption()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  UPDATE public.salon_gift_cards
    SET balance_cents = LEAST(initial_cents, balance_cents + OLD.amount_cents),
        updated_at = now()
    WHERE id = OLD.gift_card_id;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS salon_gift_card_redemptions_revert ON public.salon_gift_card_redemptions;
CREATE TRIGGER salon_gift_card_redemptions_revert
  AFTER DELETE ON public.salon_gift_card_redemptions
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_salon_gift_card_revert_redemption();

ALTER TABLE public.salon_gift_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salon_gift_card_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners manage gift cards - all"
  ON public.salon_gift_cards
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.store_profiles sp
      WHERE sp.id = salon_gift_cards.store_id
        AND sp.owner_id = (SELECT auth.uid())
    )
    OR public.has_role((SELECT auth.uid()), 'admin')
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.store_profiles sp
      WHERE sp.id = salon_gift_cards.store_id
        AND sp.owner_id = (SELECT auth.uid())
    )
    OR public.has_role((SELECT auth.uid()), 'admin')
  );

CREATE POLICY "Owners manage gift card redemptions - all"
  ON public.salon_gift_card_redemptions
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.store_profiles sp
      WHERE sp.id = salon_gift_card_redemptions.store_id
        AND sp.owner_id = (SELECT auth.uid())
    )
    OR public.has_role((SELECT auth.uid()), 'admin')
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.store_profiles sp
      WHERE sp.id = salon_gift_card_redemptions.store_id
        AND sp.owner_id = (SELECT auth.uid())
    )
    OR public.has_role((SELECT auth.uid()), 'admin')
  );

-- Public balance lookup. The customer types their code on /gift-card and we
-- only return data if a card exists with exactly that code, so the function
-- doubles as a cheap rate-limit-friendly enumeration guard (a stranger can't
-- iterate card ids).
CREATE OR REPLACE FUNCTION public.salon_public_gift_card_lookup(p_code TEXT)
RETURNS TABLE (
  store_id UUID,
  store_name TEXT,
  initial_cents INTEGER,
  balance_cents INTEGER,
  is_active BOOLEAN,
  expires_at TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    gc.store_id,
    sp.name AS store_name,
    gc.initial_cents,
    gc.balance_cents,
    gc.is_active,
    gc.expires_at
  FROM public.salon_gift_cards gc
  JOIN public.store_profiles sp ON sp.id = gc.store_id
  WHERE upper(gc.code) = upper(p_code)
    AND sp.is_active = true
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.salon_public_gift_card_lookup(TEXT) TO anon, authenticated;
