// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
const REMEMBER_ME_KEY = "zivo_remember_me";
const SUPABASE_PROJECT_REF =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  (SUPABASE_URL ? new URL(SUPABASE_URL).hostname.split(".")[0] : "");
const SUPABASE_AUTH_KEY = `sb-${SUPABASE_PROJECT_REF}-auth-token`;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Don't throw at module load — that crashes the whole React tree and leaves
  // visitors with a blank white page (seen on zivollc.com when the production
  // build was published without the VITE_SUPABASE_* env vars baked in).
  // Log loudly so the issue is still obvious in DevTools, but let the app boot.
  // eslint-disable-next-line no-console
  console.error(
    "[supabase/client] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY — " +
    "Supabase calls will fail until the site is re-published with env vars."
  );
}

function isSupabaseSecretKey(key: string): boolean {
  if (key.startsWith("sb_secret_")) return true;
  const [, payload] = key.split(".");
  if (!payload) return false;
  try {
    const normalized = payload.replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const json = JSON.parse(atob(padded));
    return json?.role === "service_role";
  } catch {
    return false;
  }
}

if (isSupabaseSecretKey(SUPABASE_PUBLISHABLE_KEY)) {
  throw new Error("VITE_SUPABASE_PUBLISHABLE_KEY must be a publishable/anon key, not a secret or service-role key.");
}

const isNativePlatform = Capacitor.isNativePlatform();

// ── Web: synchronous localStorage / sessionStorage (remember-me aware) ──
const getPreferredStorage = (): Storage => {
  try {
    const remembered = localStorage.getItem(REMEMBER_ME_KEY) !== "false";
    return remembered ? localStorage : sessionStorage;
  } catch {
    return localStorage;
  }
};

const webAuthStorage: Storage = {
  getItem: (key: string) => getPreferredStorage().getItem(key),
  setItem: (key: string, value: string) => {
    getPreferredStorage().setItem(key, value);
  },
  removeItem: (key: string) => {
    try { localStorage.removeItem(key); } catch { /* noop */ }
    try { sessionStorage.removeItem(key); } catch { /* noop */ }
  },
  clear: () => {
    getPreferredStorage().clear();
  },
  key: (index: number) => getPreferredStorage().key(index),
  get length() {
    return getPreferredStorage().length;
  },
};

// ── Native: async @capacitor/preferences (UserDefaults / SharedPreferences) ──
// A WKWebView's *synchronous* localStorage read can stall the JS main thread on a
// cold start (observed on the iOS simulator: the auth client hangs and the SSO
// "Connecting your ZIVO account…" spinner never resolves — even setTimeout-based
// timeouts can't fire). Preferences is async and disk-durable, so the session read
// never blocks the thread AND survives the native app-switch / cold relaunch.
// Every native storage call is timeout-guarded: if the WKWebView↔native bridge
// stalls on a cold start (it can on the iOS simulator), the op falls back to
// "no value" after 4s so the app proceeds to login instead of hanging on boot.
const storageOpTimeout = <T,>(p: Promise<T>, fallback: T): Promise<T> =>
  Promise.race([p, new Promise<T>((resolve) => setTimeout(() => resolve(fallback), 4000))]);

const nativeAuthStorage = {
  getItem: async (key: string): Promise<string | null> => {
    try {
      const { value } = await storageOpTimeout(Preferences.get({ key }), { value: null });
      if (value != null) return value;
      // One-time migration so the storage switch doesn't sign existing users out:
      // lift a session still living in localStorage into Preferences, then drop it.
      try {
        const legacy = localStorage.getItem(key);
        if (legacy != null) {
          await storageOpTimeout(Preferences.set({ key, value: legacy }), undefined);
          try { localStorage.removeItem(key); } catch { /* ignore */ }
          return legacy;
        }
      } catch { /* ignore */ }
      return null;
    } catch {
      return null;
    }
  },
  setItem: async (key: string, value: string): Promise<void> => {
    try { await storageOpTimeout(Preferences.set({ key, value }), undefined); } catch { /* ignore */ }
  },
  removeItem: async (key: string): Promise<void> => {
    try { await storageOpTimeout(Preferences.remove({ key }), undefined); } catch { /* ignore */ }
    try { localStorage.removeItem(key); } catch { /* ignore */ }
  },
};

export function setRememberMePreference(remember: boolean) {
  // Native sessions always live in durable native storage; the web-only shuffle
  // between localStorage and sessionStorage doesn't apply there.
  if (isNativePlatform) {
    try { localStorage.setItem(REMEMBER_ME_KEY, remember ? "true" : "false"); } catch { /* ignore */ }
    return;
  }
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? "true" : "false");
    if (remember) {
      const token = sessionStorage.getItem(SUPABASE_AUTH_KEY);
      if (token) {
        localStorage.setItem(SUPABASE_AUTH_KEY, token);
        sessionStorage.removeItem(SUPABASE_AUTH_KEY);
      }
    } else {
      const token = localStorage.getItem(SUPABASE_AUTH_KEY);
      if (token) {
        sessionStorage.setItem(SUPABASE_AUTH_KEY, token);
        localStorage.removeItem(SUPABASE_AUTH_KEY);
      }
    }
  } catch {
    // Ignore storage failures in private mode or restricted webviews.
  }
}

// Session storage adapter: durable async native store on device, the
// remember-me-aware web store in the browser.
const authStorage = isNativePlatform ? nativeAuthStorage : webAuthStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fall back to harmless placeholders when env vars are missing so createClient
// doesn't throw at module load (a throw here blanks out the whole React tree).
const SAFE_URL = SUPABASE_URL || "https://missing-env.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY || "missing-env-key";

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  db: {
    schema: "public",
  },
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Use an in-memory lock instead of the Web Locks API. navigator.locks can
    // deadlock inside a native WebView (auth calls hang forever, e.g. the SSO
    // "Connecting with ZIVO…" spinner). processLock is Supabase's recommended
    // lock for non-browser / mobile runtimes.
    lock: processLock,
  },
  global: {
    // Keep TCP connection alive across requests to avoid cold-start latency
    // on mobile networks (saves ~100-300 ms per lightweight read after idle).
    // Do not set keepalive on uploads/mutations: browsers cap keepalive
    // request bodies at roughly 64KB, which breaks real photo/video sends.
    fetch: (url, options: RequestInit = {}) => {
      const method = (options.method || "GET").toUpperCase();
      const canKeepAlive = !options.body && (method === "GET" || method === "HEAD");
      return fetch(url, canKeepAlive ? { ...options, keepalive: true } : options);
    },
  },
  realtime: {
    params: {
      // Reduce heartbeat interval so the WS connection stays alive on
      // aggressive NAT/firewalls (default is 30 s, 20 s is safer).
      heartbeatIntervalMs: 20_000,
    },
    timeout: 30_000,
  },
});
