// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';
import {
  ZIVO_SOFTWARE_SUPABASE_PUBLISHABLE_KEY,
  ZIVO_SOFTWARE_SUPABASE_URL,
  isZivoSoftwareHost,
} from '@/config/autoRepairDomain';
import {
  ZIVO_TRAVEL_SUPABASE_PUBLISHABLE_KEY,
  ZIVO_TRAVEL_SUPABASE_URL,
  ZIVO_TRAVEL_USE_DEDICATED_BACKEND,
  isZivoTravelHost,
} from '@/config/zivoTravelDomain';
import {
  ZIVO_DRIVER_SUPABASE_PUBLISHABLE_KEY,
  ZIVO_DRIVER_SUPABASE_URL,
  isZivoDriverHost,
} from '@/config/zivoDriverDomain';

const runtimeHostname = typeof window !== "undefined" ? window.location.hostname : "";
const useZivoSoftwareBackend = isZivoSoftwareHost(runtimeHostname);
const useZivoTravelBackend =
  isZivoTravelHost(runtimeHostname) &&
  ZIVO_TRAVEL_USE_DEDICATED_BACKEND &&
  Boolean(ZIVO_TRAVEL_SUPABASE_URL && ZIVO_TRAVEL_SUPABASE_PUBLISHABLE_KEY);
const useZivoDriverBackend =
  isZivoDriverHost(runtimeHostname) &&
  Boolean(ZIVO_DRIVER_SUPABASE_URL && ZIVO_DRIVER_SUPABASE_PUBLISHABLE_KEY);

const MAIN_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const MAIN_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";
const MISSING_SUPABASE_CONFIG_URL = "https://zivo-supabase-env-required.invalid";
const MISSING_SUPABASE_CONFIG_KEY = "missing-supabase-publishable-key";
const hasMainSupabaseConfig = Boolean(MAIN_SUPABASE_URL && MAIN_SUPABASE_PUBLISHABLE_KEY);

export const AUTH_SUPABASE_URL = MAIN_SUPABASE_URL || MISSING_SUPABASE_CONFIG_URL;
export const AUTH_SUPABASE_PUBLISHABLE_KEY =
  MAIN_SUPABASE_PUBLISHABLE_KEY || MISSING_SUPABASE_CONFIG_KEY;

export const DATA_SUPABASE_URL = useZivoSoftwareBackend
  ? ZIVO_SOFTWARE_SUPABASE_URL
  : useZivoTravelBackend
  ? ZIVO_TRAVEL_SUPABASE_URL
  : useZivoDriverBackend
  ? ZIVO_DRIVER_SUPABASE_URL
  : AUTH_SUPABASE_URL;
export const DATA_SUPABASE_PUBLISHABLE_KEY = useZivoSoftwareBackend
  ? ZIVO_SOFTWARE_SUPABASE_PUBLISHABLE_KEY
  : useZivoTravelBackend
  ? ZIVO_TRAVEL_SUPABASE_PUBLISHABLE_KEY
  : useZivoDriverBackend
  ? ZIVO_DRIVER_SUPABASE_PUBLISHABLE_KEY
  : AUTH_SUPABASE_PUBLISHABLE_KEY;

// Backward-compatible data endpoint exports. New auth-sensitive code should use
// AUTH_SUPABASE_URL/AUTH_SUPABASE_PUBLISHABLE_KEY or authSupabase explicitly.
export const SUPABASE_URL = DATA_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = DATA_SUPABASE_PUBLISHABLE_KEY;
const REMEMBER_ME_KEY = "zivo_remember_me";
const useDedicatedSoftwareAuth =
  useZivoSoftwareBackend &&
  Boolean(ZIVO_SOFTWARE_SUPABASE_URL && ZIVO_SOFTWARE_SUPABASE_PUBLISHABLE_KEY);
const EFFECTIVE_AUTH_SUPABASE_URL = useDedicatedSoftwareAuth
  ? ZIVO_SOFTWARE_SUPABASE_URL
  : AUTH_SUPABASE_URL;
const EFFECTIVE_AUTH_SUPABASE_KEY = useDedicatedSoftwareAuth
  ? ZIVO_SOFTWARE_SUPABASE_PUBLISHABLE_KEY
  : AUTH_SUPABASE_PUBLISHABLE_KEY;
const EFFECTIVE_DATA_SUPABASE_URL = DATA_SUPABASE_URL || EFFECTIVE_AUTH_SUPABASE_URL;
const EFFECTIVE_DATA_SUPABASE_KEY = DATA_SUPABASE_PUBLISHABLE_KEY || EFFECTIVE_AUTH_SUPABASE_KEY;
const SUPABASE_PROJECT_REF =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  (EFFECTIVE_AUTH_SUPABASE_URL ? new URL(EFFECTIVE_AUTH_SUPABASE_URL).hostname.split(".")[0] : "");
const SUPABASE_AUTH_KEY = `sb-${SUPABASE_PROJECT_REF}-auth-token`;

if (!hasMainSupabaseConfig) {
  // Don't throw at module load — that crashes the whole React tree and leaves
  // visitors with a blank white page (seen on zivosmedia.com when the production
  // build was published without the VITE_SUPABASE_* env vars baked in).
  // Log loudly so the issue is still obvious in DevTools, but let the app boot.
  console.error(
    "[supabase/client] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY — " +
    "using a disabled placeholder endpoint until the site is re-published with env vars."
  );
}

function isSupabaseSecretKey(key: string): boolean {
  if (key.startsWith("sb_secret_")) return true;
  const [, payload] = key.split(".");
  if (!payload) return false;
  try {
    const normalized = payload.replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const json = JSON.parse(atob(padded));
    return json?.role === "service_role";
  } catch {
    return false;
  }
}

if (isSupabaseSecretKey(AUTH_SUPABASE_PUBLISHABLE_KEY)) {
  throw new Error("VITE_SUPABASE_PUBLISHABLE_KEY must be a publishable/anon key, not a secret or service-role key.");
}

if (isSupabaseSecretKey(DATA_SUPABASE_PUBLISHABLE_KEY)) {
  throw new Error("Dedicated domain Supabase publishable key must be a publishable/anon key, not a secret or service-role key.");
}

const isNativePlatform = Capacitor.isNativePlatform();

// ── Web: synchronous localStorage / sessionStorage (remember-me aware) ──
const getPreferredStorage = (): Storage => {
  try {
    const remembered = localStorage.getItem(REMEMBER_ME_KEY) !== "false";
    return remembered ? localStorage : sessionStorage;
  } catch {
    return localStorage;
  }
};

const webAuthStorage: Storage = {
  getItem: (key: string) => getPreferredStorage().getItem(key),
  setItem: (key: string, value: string) => {
    getPreferredStorage().setItem(key, value);
  },
  removeItem: (key: string) => {
    try { localStorage.removeItem(key); } catch { /* noop */ }
    try { sessionStorage.removeItem(key); } catch { /* noop */ }
  },
  clear: () => {
    getPreferredStorage().clear();
  },
  key: (index: number) => getPreferredStorage().key(index),
  get length() {
    return getPreferredStorage().length;
  },
};

// ── Native: async @capacitor/preferences (UserDefaults / SharedPreferences) ──
// A WKWebView's *synchronous* localStorage read can stall the JS main thread on a
// cold start (observed on the iOS simulator: the auth client hangs and the SSO
// "Connecting your ZIVO account…" spinner never resolves — even setTimeout-based
// timeouts can't fire). Preferences is async and disk-durable, so the session read
// never blocks the thread AND survives the native app-switch / cold relaunch.
// Every native storage call is timeout-guarded: if the WKWebView↔native bridge
// stalls on a cold start (it can on the iOS simulator), the op falls back to
// "no value" after 4s so the app proceeds to login instead of hanging on boot.
const storageOpTimeout = <T,>(p: Promise<T>, fallback: T): Promise<T> =>
  Promise.race([p, new Promise<T>((resolve) => setTimeout(() => resolve(fallback), 4000))]);

const nativeAuthStorage = {
  getItem: async (key: string): Promise<string | null> => {
    try {
      const { value } = await storageOpTimeout(Preferences.get({ key }), { value: null });
      if (value != null) return value;
      // One-time migration so the storage switch doesn't sign existing users out:
      // lift a session still living in localStorage into Preferences, then drop it.
      try {
        const legacy = localStorage.getItem(key);
        if (legacy != null) {
          await storageOpTimeout(Preferences.set({ key, value: legacy }), undefined);
          try { localStorage.removeItem(key); } catch { /* ignore */ }
          return legacy;
        }
      } catch { /* ignore */ }
      return null;
    } catch {
      return null;
    }
  },
  setItem: async (key: string, value: string): Promise<void> => {
    try { await storageOpTimeout(Preferences.set({ key, value }), undefined); } catch { /* ignore */ }
  },
  removeItem: async (key: string): Promise<void> => {
    try { await storageOpTimeout(Preferences.remove({ key }), undefined); } catch { /* ignore */ }
    try { localStorage.removeItem(key); } catch { /* ignore */ }
  },
};

export function setRememberMePreference(remember: boolean) {
  // Native sessions always live in durable native storage; the web-only shuffle
  // between localStorage and sessionStorage doesn't apply there.
  if (isNativePlatform) {
    try { localStorage.setItem(REMEMBER_ME_KEY, remember ? "true" : "false"); } catch { /* ignore */ }
    return;
  }
  try {
    localStorage.setItem(REMEMBER_ME_KEY, remember ? "true" : "false");
    if (remember) {
      const token = sessionStorage.getItem(SUPABASE_AUTH_KEY);
      if (token) {
        localStorage.setItem(SUPABASE_AUTH_KEY, token);
        sessionStorage.removeItem(SUPABASE_AUTH_KEY);
      }
    } else {
      const token = localStorage.getItem(SUPABASE_AUTH_KEY);
      if (token) {
        sessionStorage.setItem(SUPABASE_AUTH_KEY, token);
        localStorage.removeItem(SUPABASE_AUTH_KEY);
      }
    }
  } catch {
    // Ignore storage failures in private mode or restricted webviews.
  }
}

// Session storage adapter: durable async native store on device, the
// remember-me-aware web store in the browser.
const authStorage = isNativePlatform ? nativeAuthStorage : webAuthStorage;

const sharedClientOptions = {
  db: {
    schema: "public",
  },
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    // Keep TCP connection alive across requests to avoid cold-start latency
    // on mobile networks (saves ~100-300 ms per lightweight read after idle).
    // Do not set keepalive on uploads/mutations: browsers cap keepalive
    // request bodies at roughly 64KB, which breaks real photo/video sends.
    fetch: (url, options: RequestInit = {}) => {
      const method = (options.method || "GET").toUpperCase();
      const canKeepAlive = !options.body && (method === "GET" || method === "HEAD");
      return fetch(url, canKeepAlive ? { ...options, keepalive: true } : options);
    },
  },
  realtime: {
    params: {
      // Reduce heartbeat interval so the WS connection stays alive on
      // aggressive NAT/firewalls (default is 30 s, 20 s is safer).
      heartbeatIntervalMs: 20_000,
    },
    timeout: 30_000,
  },
} as const;

export const authSupabase = createClient<Database>(
  EFFECTIVE_AUTH_SUPABASE_URL,
  EFFECTIVE_AUTH_SUPABASE_KEY,
  sharedClientOptions,
);

export const dataSupabase = createClient<Database>(EFFECTIVE_DATA_SUPABASE_URL, EFFECTIVE_DATA_SUPABASE_KEY, {
  ...sharedClientOptions,
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
  accessToken: async () => {
    const { data } = await authSupabase.auth.getSession();
    return data.session?.access_token ?? null;
  },
});

// Import the routed client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// Compatibility note: existing code keeps using `supabase.from`,
// `supabase.functions`, `supabase.storage`, and `supabase.channel` against the
// active data project. `supabase.auth` follows the matching auth project on
// dedicated software domains so owner checks compare user IDs from the same
// Supabase project as the workspace data.
export const supabase = dataSupabase as typeof dataSupabase & {
  auth: typeof authSupabase.auth;
};
(supabase as unknown as { auth: typeof authSupabase.auth }).auth = authSupabase.auth;
